### ISSUE TITLE
Plasma Probem in nvidia mode

### ISSUE THREAD

**Issue by ali-masoudi** [Askannz/optimus-manager#289] opened 2020-07-09 15:10 UTC
hi guys
when I switch to Nvidia mode, I can open apps via keyboard hotkeys but no plasma-desktop
desktop only shows after executing:
kquitapp5 plasmashell && kstart5 plasmashell

any idea why?

**Comment by Askannz** [comment] 2020-07-25 00:15
Hmm, you're not the first one to report such this issue, but I can't reproduce it and it's rather hard to debug.

Could you try disabling the KScreen service in KDE, and see if it still happens ? (System Settings -> Startup and Shutdown -> Background Services -> Uncheck KScreen 2 -> Apply)

**Comment by areynaldos** [comment] 2020-09-17 18:24
@Askannz , I just started using optimus-manager and have exactly the same problem.

Thanks for pointing out that quitting and restarting plasmashell works... I was just trying to restart without success...

I tried disabling KScreen2 to no avail. Please let me know if I can submit any additional information that may help pinpoint the problem. I will look for log information when I have more time later.

**Comment by Askannz** [comment] 2020-09-19 08:52
@areynaldos I'm assuming you are using SDDM. Do you have auto-login enabled ? If yes, what happens if you disable it ? Does the login screen show up properly on the screen ?

Also, I'd appreciate if you could send the latest entry from `/var/log/optimus-manager/switch/` after reproducing the bug. Thanks :slightly_smiling_face:

**Comment by areynaldos** [comment] 2020-09-20 20:30
@Askannz :

Yes, using SDDM, but with login screen.

Upon reboot, the login screen shows correct. Then I login and there's just a blank screen. However, I can run Krunner to launch apps (which won't show) or commands. If I had windows open from a previous session, they do show up without window borders.

After quitting and restarting plasmashell everything works OK.

Now, if I log out from an existing session, the login screen does not show.

Following your comments, here are the contents of `/var/log/optimus-manager/switch` latest file, after I rebooted, logged in through a properly displayed SDDM login screen, and then coming into a black screen:

```
[358] INFO: # Xorg pre-start hook
[359] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'nvidia', 'current_mode': None}
[359] INFO: Requested mode is: nvidia
[359] INFO: Checking for GDM display servers
[3157] INFO: Available modules: ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[3158] INFO: Unloading modules ['nouveau'] (if loaded)
[3382] INFO: Loading module nvidia
[3637] INFO: Loading module nvidia_drm
[4254] INFO: Loaded extra Intel Xorg options (0 lines)
[4268] INFO: Loaded extra Intel Xorg options (0 lines)
[4270] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
[4270] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20200920T125922', 'requested_mode': 'nvidia'}
[4271] INFO: Xorg pre-start hook completed successfully.
[8] INFO: # Xorg post-start hook
[8] INFO: Running xrandr commands
[194] INFO: Running /etc/optimus-manager/xsetup-nvidia.sh
[243] INFO: Writing state {'type': 'done', 'switch_id': '20200920T125922', 'current_mode': 'nvidia'}
[244] INFO: Xorg post-start hook completed successfully.

```

Thanks for replying and looking into it...

**Comment by kayg04** [comment] 2020-10-17 13:09
I am facing the same issue. Here's my log after rebooting into "Nvidia" mode.

```
[28] INFO: # Xorg pre-start hook
[28] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'nvidia', 'current_mode': None}
[28] INFO: Requested mode is: nvidia
[28] INFO: Checking for GDM display servers
[1092] INFO: Available modules: ['nouveau', 'bbswitch', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[1093] INFO: Unloading modules ['nouveau'] (if loaded)
[1097] INFO: Loading module bbswitch
[1102] INFO: Setting GPU power to ON via bbswitch
[1122] INFO: Loading module nvidia
[2017] INFO: Loading module nvidia_drm
[2862] INFO: Loaded extra Intel Xorg options (0 lines)
[2862] INFO: Loaded extra Intel Xorg options (0 lines)
[2862] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
[2862] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20201017T183401', 'requested_mode': 'nvidia'}
[2862] INFO: Xorg pre-start hook completed successfully.
[4] INFO: # Xorg post-start hook
[4] INFO: Running xrandr commands
[2614] INFO: Running /etc/optimus-manager/xsetup-nvidia.sh
[2650] INFO: Writing state {'type': 'done', 'switch_id': '20201017T183401', 'current_mode': 'nvidia'}
[2652] INFO: Xorg post-start hook completed successfully.
```

**Comment by areynaldos** [comment] 2021-01-31 01:57
@Askannz , I can report now that the problem disappeared some time in the last couple of releases. I am running KDE Plasma 5.20.5 and optimus-manager 1.3

Everything works as expected!

**Comment by creidhne-a16i** [comment] 2021-02-27 22:18
I now have exactly the same problem. Disabling Kscreen2 causes the taskbar to not start even after I explicitly restart plasmashell. Requested log looks exactly like ones pasted before.

**Comment by nwildner** [comment] 2024-07-01 10:33
Hello @creidhne-a16i . Were you able to test this out again using `optimus-manager-git`?

Since @areynaldos reported that it was solved, we'll be closing this case if no additional input is provided.

Have a nice week ahead.

**Comment by creidhne-a16i** [comment] 2024-07-01 12:13
Hei @nwildner 
This was over 3  years ago, I no longer have the laptop in question to test. Feel free to close the issue =) 
Thanks and likewise have a nice week!

**Closed** 2024-07-01 12:22 UTC
Labels: bug
