### ISSUE TITLE
Black screen when switching to nvidia (can enter password)

### ISSUE THREAD

**Issue by FancyBanana** [Askannz/optimus-manager#70] opened 2019-04-20 23:57 UTC
**Describe the bug**
When i switch to nvidia (or boot to nvidia) sddm does not display anything. I still can enter password and log in to plasma.

**System info**
Please include :
- Your distribution
  manjaro linux 18.0.4
- Your desktop manager
   KDE
- You display manager
  SDDM
- Your laptop model, if you think it could be related to the problem
  Asus f751lk (nvidia 850m) (i don't think it's the problem)

**Logs**
Please attach the following logs (if you are able to):
[Xorg log](https://pastebin.com/8vnyhkZz)
[SDDM log](https://pastebin.com/cwMYjhVc)
[Optimus-manager log](https://pastebin.com/np9RpZhg)

**Comment by inzar98** [comment] 2019-04-21 10:31
Omg tried login on black screen and worked !

https://github.com/Askannz/optimus-manager/issues/64

@Askannz Our issues are same :)

**Comment by inzar98** [comment] 2019-04-22 14:13
There is no issue on Arch.
It is specific to Manjaro

**Comment by Askannz** [comment] 2019-04-22 23:27
Alright, sounds like GPU switching works but Prime is not set up for some reason.
Once logged into your session in Nvidia mode, what is the output of the command `xrandr --listproviders ` for you ?

**Comment by FancyBanana** [comment] 2019-04-23 03:38
Here it is:  
```
Providers: number : 2
Provider 0: id: 0x238 cap: 0x1, Source Output crtcs: 0 outputs: 0 associated providers: 1 name:NVIDIA-0
Provider 1: id: 0x45 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 3 associated providers: 1 name:modesetting
```

**Comment by Socterean** [comment] 2019-04-23 19:27
I just entered here to post the same issue. On optimus-manager v0.8.2 when switching to Nvidia the screen stay black until entering the password. After the password is inserted the login screen appears small in the top left part of the screen and shows the loading animation.

On v0.7.1 the issue is not occurring.

**xrandr --listproviders:**
```
Providers: number : 2
Provider 0: id: 0x2e8 cap: 0x1, Source Output crtcs: 0 outputs: 0 associated providers: 1 name:NVIDIA-0
Provider 1: id: 0x47 cap: 0xb, Source Output, Sink Output, Sink Offload crtcs: 4 outputs: 4 associated providers: 1 name:Intel
```


OS: Manjaro Linux x86_64
Host: 20217 Lenovo IdeaPad Y510P
Kernel: 5.0.5-1-MANJARO
Resolution: 1920x1080
DE: KDE 5.15.3-1
CPU: Intel i7-4700MQ (8) @ 3.400GHz
GPU: Intel 4th Gen Core Processor
GPU: NVIDIA GeForce GT 750M
Memory: 1958MiB / 7892MiB

**Comment by Askannz** [comment] 2019-05-04 07:17
Could you test the latest Git version and see if the problem persists ?
This version introduces some major changes to the way optimus-manager works, so you need to reboot after upgrading to make sure everything is reloaded up properly.

**Comment by Socterean** [comment] 2019-05-04 11:22
I have tested `optimus-manager-git` and the bug is still there.

However there is a slight difference, now the login screen background is displayed on the full screen as it should (after inserting the password blindly on the black screen), but the usual login animation I had doesn't appear anymore.

**Comment by czapnaper** [comment] 2019-05-04 14:24
I had the same problem. In my case, removing DisplayComand and DisplayStopCommand in /etc/sddm.conf helped.

**Comment by Askannz** [comment] 2019-05-05 01:13
@Socterean using the latest git version, could you post the contents of `/var/log/optimus-manager/` ?

@czapnaper those two scripts are handle Prime setup and GPU switching. If you remove them (particularly the second one), optimus-manager won't be able to switch GPUs after boot.

If you are still having issues with the latest git version, could you also post the log files from `/var/log/optimus-manager/` ?

**Comment by czapnaper** [comment] 2019-05-05 08:39
@Askannz Optimus manager provides the file /etc/sddm.conf.d/20-optimus-manager.conf which has these options. The standard configuration of sddm (/etc/sddm.conf) sets these options differently than the file provided by optimus manager.

**Comment by Askannz** [comment] 2019-05-05 08:56
@czapnaper By default, `DisplayComand` and `DisplayStopCommand` point to `/usr/share/sddm/scripts/Xsetup` and `usr/share/sddm/scripts/Xstop` which are just empty files. I don't really understand your point.

**Comment by czapnaper** [comment] 2019-05-05 10:48
When the `DisplayComand` and `DisplayStopCommand` options are set in either `/etc/sddm.conf` and `/etc/sddm.conf.d/20-optimus-manager.conf` in the latest version (git) the optimus manager will not change the graphics card. In version 0.8, when the `DisplayComand` option is set in either `/etc/sddm.conf` and `/etc/sddm.conf.d/10-optimus-manager.conf`, sddm only shows the black screen but you can log in to it. In my case.

**Comment by Socterean** [comment] 2019-05-05 12:56
>@Socterean using the latest git version, could you post the contents of `/var/log/optimus-manager/ `?

Here is [/var/log/optimus-manager/](https://pastebin.com/iy6A5XkA)

Note that I used optimus-manager --set-startup nvidia as I cannot change cards at runtime because of the situation described in #68

**Comment by Askannz** [comment] 2019-05-11 00:25
So yeah, I checked in a VM and indeed, Manjaro ships KDE with a default configuration for sddm.conf, which forces `DisplayCommand` and `DisplayStopCommand` to point to the default scripts (for no good reason).

And because this is set in the default config file and not in the drop-in folder `sddm.conf.d`, this cannot be overridden from optimus-manager :disappointed: 

For now the solution is to edit `/etc/sddm.conf` and put a `#` before the lines `DisplayCommand` and `DisplayStopCommand`.

**Comment by Askannz** [comment] 2019-06-23 02:22
Closing this issue since the original bug was probably due to the SDDM config. Feel free to reopen if needed.

**Closed by Askannz** 2019-06-23 02:22 UTC
Labels: bug
