### ISSUE TITLE
could you look into adding wayland support now with the latest advancements?

### ISSUE THREAD

**Issue by ginick** [Askannz/optimus-manager#423] opened 2021-07-16 04:50 UTC
KDE Plasma 5.22 got better support for wayland and same for Nvidia  470 .

Thank you.

**Comment by nwildner** [comment] 2024-07-01 12:04
Sup @ginick .

Closing this since it is a duplicate of #452 .

Cheers.

**Closed by nwildner** 2024-07-01 12:04 UTC
