### ISSUE TITLE
optimus-manager CLI reports issue when everything works as expected

### ISSUE THREAD

**Issue by neumannjan** [Askannz/optimus-manager#463] opened 2022-01-09 14:33 UTC
**Describe the bug**

So recently (when optimus-manager was uninstalled) I found out that I can actually run my desktop with wayland AND successfully use prime-run offloading (i.e. hybrid mode). 

My preferred setup is to have 3 options in bootloader:

* one for `optimus-manager.startup=integrated` (should use wayland),
* one for `optimus-manager.startup=hybrid` (should also use wayland),
* and one for `optimus-manager.startup=nvidia` (should probably still use xorg).

**However**, running any `optimus-manager` command reports error, even though the GPU switch actually worked as expected. In other words, everything works as I wanted it, GDM works as expected, GPU status as well; but optimus-manager reports an error. If I check the log file, it looks fine.

(Note: I don't intend to switch GPUs when the system is running, in order to avoid having to switch from wayland to xorg and vice-versa.)

**System info**

* Manjaro
* Gnome 41
* GDM
* XPS 9560
* latest stable optimus-manager

**Logs**

```
ERROR: a GPU setup was initiated but Xorg post-start hook did not run.
Log at /var/log/optimus-manager/switch/switch-20220109T161944.log
If your login manager is GDM, make sure to follow those instructions:
https://github.com/Askannz/optimus-manager#important--gnome-and-gdm-users
If your display manager is neither GDM, SDDM nor LightDM, or if you don't use one, read the wiki:
https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting
Cannot execute command because of previous errors.
```

```
[24] INFO: # Xorg pre-start hook
[24] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'integrated', 'current_mode': None}
[24] INFO: Requested mode is: integrated
[979] INFO: Available modules: ['nouveau', 'acpi_call', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[979] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[988] INFO: Loading module acpi_call
[994] INFO: Setting GPU power to OFF via acpi_call
[994] INFO: Found saved ACPI strings
[994] INFO: Sending ACPI string \_SB.PCI0.PEG0.PEGP._OFF
[1047] INFO: ACPI string \_SB.PCI0.PEG0.PEGP._OFF works, saving
[1047] INFO: Removing Nvidia from PCI bus
[2200] INFO: Writing "1" to /sys/bus/pci/devices/0000:01:00.0/remove
[2201] WARNING: acpi_call is enabled, pci_power_control option ignored.
[2238] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
[2238] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20220109T161944', 'requested_mode': 'integrated'}
[2238] INFO: Xorg pre-start hook completed successfully.
```

**Comment by neumannjan** [comment] 2022-01-09 14:34
Related issue: #452

**Comment by Askannz** [comment] 2022-04-17 02:36
closing as a duplicate of https://github.com/Askannz/optimus-manager/issues/452

**Closed by Askannz** 2022-04-17 02:36 UTC
Labels: feature request
