### ISSUE TITLE
Issues when switching back to nvidia (xrandr or bbswitch issue)

### ISSUE THREAD

**Issue by Deathray-II** [Askannz/optimus-manager#115] opened 2019-08-16 09:59 UTC
**Describe the bug**
When attempting to switch back to nvidia after having switched to intel, optimus manager will not actually switch to nvidia and will remain in intel mode.

There are two issues that I have encountered here:
1) when using the nouveau backend when switching to nvidia it will end up giving an error in the PRIME log saying `Error : cannot setup PRIME : Cannot setup PRIME : Failed to execute 'xrandr --setprovideroutputsource modesetting NVIDIA-0' : `. When checking lsmod it also states that nouveau is being used by -1, which I assume means that it is being unloaded. After that if I attempt to switch again I will encounter an error in the GPU setup log which states that it cannot unload nouveau: `Cannot setup GPU : kernel setup error : Cannot unload nouveau : Failed to execute 'modprobe -r nouveau' : modprobe: ERROR: could not remove 'nouveau': Device or resource busy`. It will then also display the standard text on TTY1 (so no Xorg session) and not allow me to switch TTY.
2) when using the bbswitch backend when switching back to nvidia it will give the following error in the GPU setup log `Cannot setup GPU : kernel setup error : bbswitch failed to set the GPU to ON`. 

A third and possibly related issue is that when I set startup mode to be intel it will get my into SDDM where I can enter my password, but as soon as I attempt to switch TTY or actually log into my desktop it will just freeze.

For the second issue I have a sneaking suspicion that this is yet another set up ACPI issues caused by the manufacturer, although it does seem to properly turn the GPU of as stated by bbswitch and as measured by some very rudimentary comparative battery test I have run myself.

**System info**
Please include :
- Distribution: Arch
- Desktop manager: KDE plasma 5.16.4
- Display manager: SDDM 0.18.6
- Laptop model: Dell G5 5587

**Logs**

[Logs when using nouveau as the backend](https://pastebin.com/CgPV2JJT)
[Logs when using bbswitch as the backend](https://pastebin.com/eVnQ2fUw)

**Comment by Olexorus** [comment] 2019-08-16 23:21
I'm having exactly the same problem (even the same error message in prime_setup.log and gpu_setup.log).

The weird (and frustrating) thing for me is that I got it to work earlier today, but then I changed/updated some other stuff, and when I wanted to use it again it didn't work anymore. I tried reverting some of the changes I made, but it didn't work, I just spent 2 hours trying to figure out how to get it to work again.

Also when I attempt to switch to Nvidia, `cat /proc/acpi/bbswitch` actually says that the GPU is powered on (which is especially weird because according to the error, doing that didn't work), and I need to disable it manually with `tee /proc/acpi/bbswitch <<< OFF`.

I'm using a Dell XPS 7590 (i7-9750H and GTX 1650), and running Manjaro on Kernel 5.2.8

**Comment by Olexorus** [comment] 2019-08-17 08:24
I noticed something else when doing some more testing. If I try to switch to my Nvidia GPU a second time, I get a different error message, probably because it's already switched on:

From gpu_setup.log
```
Optimus Manager (Setup script) version 1.1
Setting up the GPU
Checking status of optimus-manager.service
Cleaning up leftover Xorg conf
Loading config
Requested mode : nvidia
Checking for GDM display servers
Loading bbswitch module
Setting GPU power to ON via bbswitch
bbswitch reports that the GPU is ON
bbswitch is enabled, pci_power_control option ignored.
Loading Nvidia modules
Cannot setup GPU : kernel setup error : Cannot load Nvidia modules : Failed to execute 'modprobe nvidia NVreg_UsePageAttributeTable=1' : modprobe: ERROR: could not insert 'nvidia': No such device
```

**Comment by sebirdman** [comment] 2019-08-23 04:20
@Olexorus i've got the same CPU and GPU

i'm seeing the same thing reported in this thread: https://bbs.archlinux.org/viewtopic.php?pid=1794626#p1794626

**Comment by Olexorus** [comment] 2019-08-23 08:42
@sebirdman Do you also have an XPS 7590? And if so, what BIOS version are you on? Because I think I updated my BIOS from 1.1.1 or so to 1.2.3 before bbswitch broke (as I mentioned, I had it working at one point), maybe that changed something with the power management.

I did a clean reinstall since the last time I tried optimus-manager, so I decided it might be worth another try. bbswitch still doesn't work, exactly like before.

However I took another look at the nouveau switching backend, and I might have been wrong about it. Because when I'm on the Intel GPU, I can't run nvidia-smi (with the expected error message when the GPU is powered off, complaining that the driver isn't loaded), and powertop lists it with 0.0% usage. Power consumption seems to be good, but I'm not sure if the reported discharge rate in powertop is even relieable, it changes a lot and sometimes even seems a bit random to me. I have only been testing it for a few minutes, but it even seems better than before, maybe my previous setup (default Manjaro bumblebee/bbswitch configuration) didn't disable it properly (although /proc/acpi/bbswitch always reported it as off).

Is powertop a good way to see which devices are powered on or is there a better method?

**Comment by Askannz** [comment] 2019-08-24 08:22
@Deathray-II 
> For the second issue I have a sneaking suspicion that this is yet another set up ACPI issues caused by the manufacturer, although it does seem to properly turn the GPU of as stated by bbswitch and as measured by some very rudimentary comparative battery test I have run myself.

Yeah that's likely. Unfortunately those weird ACPI behaviors are very model and vendor-specific, so I can't suggest an universal fix. Best I can suggest for now is completely disabling power management by setting `switching=none` and `pci_power_control=no` and try again. If that works, try re-enabling `pci_power_control` and see if the battery life improves.

@Olexorus @sebirdman The Dell XPS 9570 is known to be broken with optimus-manager (confirmed with another user). I'm working on fixing that for the next release (as well as coverring more cases of ACPI weirdness). In the meantime, the following *may* work : set `switching=none` and `pci_power_control=yes`. To switch GPUs, use `--set-startup` + reboot instead of `--switch`.

I don't know about the XPS 7590, but the same method is worth a shot.

**Comment by sebirdman** [comment] 2019-08-24 18:04
@Olexorus i've got the thinkpad x1e gen2

@Askannz I think ultimately the best solution to date for this card in intel mode (1650 w/Turing architecture) would be something similar to what's proposed on https://github.com/Askannz/optimus-manager/issues/114 

All i've tried so far to power down this card is by removing it from the PCI bus, i'll give pci_power_control a shot and report back soon.

**Comment by Askannz** [comment] 2019-10-20 02:23
There has been some changes to the power management code in optimus-manager (in particular for XPS models), so if you were experiencing issues please update and don't forget to follow the new [power management guide](https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options).

Closing this issue since there's not much else I can do.

**Closed by Askannz** 2019-10-20 02:23 UTC
Labels: bug
