### ISSUE TITLE
Everything is laggy under nvidia/hybrid mode

### ISSUE THREAD

**Issue by elichai** [Askannz/optimus-manager#314] opened 2020-08-29 15:08 UTC
**Describe the bug**
Whenever I switch to nvidia or to hybrid mode everything starts being laggy, both simple things (terminal, browser) and obviously games.

I tried fiddling with the configuration a bit but nothing changed, what I've tried:
```
[optimus]
pci_power_control=yes

[nvidia]
modeset=yes
DPI=
```

**System info**
Please include :
- Your distribution Arch Linux 5.8.5-arch1-1 x86_64
- Your desktop manager: KDE
- You display manager: SDDM
- Your laptop model: Dell XPS 15 7590 (GTX 1650, Intel i9-9980HK).
- The version of optimus-manager you are using : latest stable release (Optimus Manager (Client) version 1.3)
- Your custom optimus-manager configuration file at `/etc/optimus-manager/optimus-manager.conf`, if you made one

**Logs**
switch:
```
[5] INFO: # Xorg pre-start hook
[5] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'hybrid', 'current_mode': 'intel'}
[5] INFO: Requested mode is: hybrid
[5] INFO: Checking for GDM display servers
[668] INFO: Available modules: ['nouveau', 'bbswitch', 'acpi_call', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[668] INFO: Unloading modules ['nouveau'] (if loaded)
[680] INFO: Setting Nvidia PCI power state to on
[722] INFO: Loading module nvidia
[724] INFO: Loading module nvidia_drm
[1177] INFO: Loaded extra Intel Xorg options (0 lines)
[1177] INFO: Loaded extra Intel Xorg options (0 lines)
[1177] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
[1177] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20200829T175758', 'requested_mode': 'hybrid'}
[1177] INFO: Xorg pre-start hook completed successfully.
[2] INFO: # Xorg post-start hook
[2] INFO: Running /etc/optimus-manager/xsetup-hybrid.sh
[6] INFO: Writing state {'type': 'done', 'switch_id': '20200829T175758', 'current_mode': 'hybrid'}
[6] INFO: Xorg post-start hook completed successfully.
```

**Comment by Askannz** [comment] 2020-09-13 01:25
Well, that's new. Is there anything in task manager/htop that has an abnormally high CPU usage ? Anything fishy in `dmesg` or `nvidia-smi` ?

**Comment by elichai** [comment] 2020-09-13 09:59
> Well, that's new. Is there anything in task manager/htop that has an abnormally high CPU usage ? Anything fishy in `dmesg` or `nvidia-smi` ?

didn't check `dmesg`, but both `htop` and `nvidia-smi` showed nothing out of the ordinary.
this is both for games and with regular usage.

**Comment by KannebTo** [comment] 2020-09-21 15:22
@elichai did you mean video lag or input lag? In my case it's a strange input lag for a couple of hundred ms when running on NVIDIA, that happens once a minute or so. But i have no problems while gaming. It could be some auto-suspend issue of input devices, but this makes no sense because it happens also while typing. `/var/log/Xorg.0.log` says: `client bug: event processing lagging behind by 1287ms, your system is too slow`. But there is no process with high CPU usage. I have not noticed this on Intel graphics.

**Comment by Askannz** [comment] 2020-09-24 04:34
@elichai do you use an external monitor ? The new Reverse Prime (that allows to use the Nvidia outputs in hybrid mode) is a little buggy at the moment: https://forums.developer.nvidia.com/t/the-all-new-outputsink-feature-aka-reverse-prime/129828/31

**Comment by dgaus** [comment] 2020-09-29 20:42
I am having a similar issue, hybrid mode works fine using the internal display, but as soon as I plug in an external monitor everything becomes extremely choppy. For example playing a 4k video uses 50% of all cores. Thank for the nvidia link, guess we will have to wait a bit.

**Comment by elichai** [comment] 2020-10-05 08:55
> @elichai do you use an external monitor ? The new Reverse Prime (that allows to use the Nvidia outputs in hybrid mode) is a little buggy at the moment: https://forums.developer.nvidia.com/t/the-all-new-outputsink-feature-aka-reverse-prime/129828/31

yes, I use 2 external monitors

**Comment by xerus2000** [comment] 2020-10-24 09:24
Similar problem here on a HP Pavilion laptop running Arch:
- in `intel` mode, the external monitor is ignored
- in `nvidia` and `hybrid` mode, both monitors work, but the external one lags, while the internal one is just fine

And I just realized that removing optimus-manager completely produces that same behavior...

**Comment by DenisValcke** [comment] 2021-06-15 06:44
I'm having the same issue in hybrid mode my external monitor is very choppy and my internal monitor is smooth as can be.

Current config:
```
[optimus]
startup_mode=hybrid
startup_auto_battery_mode=hybrid
startup_auto_extpower_mode=hybrid

[intel]
driver=intel
tearfree=yes

[nvidia]
modeset=yes
PAT=yes
```

Working on nvidia only leaves me with the same issue @KannebTo is having and that is mentioned here:
https://github.com/Askannz/optimus-manager/issues/398#issuecomment-846388362

It seems that every mode has some issue that makes it hard to work with. Starting to consider moving away from Gnome because the nvidia only issues seem related to Gnome/Mutter.

**Comment by qomaeng** [comment] 2021-11-04 03:25
I fixed input device event processing lagging somehow.

Before fixing the problem I
- have hybrid graphic card (intel, nvidia)
- used optimus-manager to change the graphic card (intel, hybrid, nvidia)
  - only nvidia mode has input lag problem
- made Nvidia turned off when not in use using [this](https://wiki.archlinux.org/title/PRIME#PCI-Express_Runtime_D3_(RTD3)_Power_Management) and also set optimus-manager config `dynamic_power_management=fine`

And fixed the problem
- after enabling the systemd service [nvidia-persistenced](https://us.download.nvidia.com/XFree86/Linux-x86_64/465.27/README/nvidia-persistenced.html)

Even though Xorg log file says there are input event processing lag but it's small(0~30ms)

---

Here is my settings about 
Nvidia power management:

- /etc/udev/rules.d/80-nvidia-pm.rules
```
# Enable runtime PM for NVIDIA VGA/3D controller devices on driver bind
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="auto"
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="auto"

# Disable runtime PM for NVIDIA VGA/3D controller devices on driver unbind
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="on"
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="on"
```

- /etc/modprobe.d/nvidia-pm.conf
```
options nvidia "NVreg_DynamicPowerManagement=0x02"
```

- nvidia-persistenced.service (systemd service)
```
● nvidia-persistenced.service - NVIDIA Persistence Daemon
     Loaded: loaded (/usr/lib/systemd/system/nvidia-persistenced.service; enabled; vendor preset: disabled)
     Active: active (running)
```

And optimus-manager:
```
[amd]                                                                                                                                                                                                                                         
DRI=3    
driver=modesetting    
tearfree=    
    
[intel]    
DRI=3    
accel=    
driver=modesetting    
modeset=yes    
tearfree=    
    
[nvidia]    
DPI=96    
PAT=yes    
allow_external_gpus=no    
dynamic_power_management=fine    
ignore_abi=no    
modeset=yes    
options=overclocking    
    
[optimus]    
auto_logout=yes    
pci_power_control=no    
pci_remove=no    
pci_reset=no    
startup_auto_battery_mode=integrated    
startup_auto_extpower_mode=nvidia    
startup_mode=nvidia    
switching=none
```

**Comment by andrewaclear** [comment] 2023-03-08 07:35
Is there a fix for this as I also have this issue I have the Legion 7i with the RTX 3070 and Intel i7 processor. When I set Optimus to _hybrid_ the external monitor works but goes very choppy and slow when I close the lid (shut off my builtin display) and doesn't turn on at all in _integrated_ mode.

**Comment by andrewaclear** [comment] 2023-03-08 07:36
Is there a fix for this as I also have this issue I have the Legion 7i with the RTX 3070 and Intel i7 processor? When I set Optimus to _hybrid_ the external monitor works but goes very choppy and slow when I close the lid (shut off my builtin display) and doesn't turn on at all in _integrated_ mode.

**Comment by andrewaclear** [comment] 2023-03-24 17:44
But my issue is **only** on the **_external monitor_** when my laptop primary monitor is _disabled_.

**Comment by xeruf** [comment] 2023-03-26 15:02
> But my issue is **only** on the **_external monitor_** when my laptop primary monitor is _disabled_.

Had similar observations on my HP Pavilion before

**Comment by alexanderwwagner** [comment] 2024-02-15 10:35
Any uptates here?
I have the same issue if I connect an external monitor.

**Comment by Xefreh** [comment] 2024-02-24 12:02
same I'm having the same issue on my ROG Strix G733QS laptop, when I switch to nvidia mode, my integrated monitor is really not smooth.

**Comment by nwildner** [comment] 2024-07-02 13:53
Closing as a duplicate of: 

 - #498

Let's focus our efforts on cases related to "`nvidia` mode is sluggish or choppy on laptop screen" concentrated on that case.

Have a nice week ahead

**Closed by nwildner** 2024-07-02 13:53 UTC
Labels: hardware
