### ISSUE TITLE
Incorrect DPI settings on KDE Plasma when switched to Nvidia

### ISSUE THREAD

**Issue by Socterean** [Askannz/optimus-manager#67] opened 2019-04-14 13:49 UTC
**Describe the bug**
Currently, at leas with my video card, everytime I want to switch on to Nvidia, no matter what solution I use (optimus-manager, nvidia-xrun, optimus-switch, etc.) the text changes and becomes smaller, and also the titles of apps as you can see in the pictures below:

- Normal DPI settings when on Intel:
![Screenshot_intel](https://user-images.githubusercontent.com/38301587/56093627-b89e4000-5ed3-11e9-8d04-745737dfe18b.png)
- Abnormal DPI settings when on Nvidia:
![Screenshot_nvidia](https://user-images.githubusercontent.com/38301587/56093634-cd7ad380-5ed3-11e9-91d2-d4c6198fa1ff.png)

**Found a fix**
Currently I have found a fix for this by adding two lines in the `/etc/optimus-manager/xorg-nvidia.conf`

```
Option "UseEdidDpi" "FALSE" (it seems to work without this line as well)
Option "DPI" "96 x 96"
```

I know that this is not an optimus-manager specific issue, but it would be awesome if somehow this workaround can be included in a release of optimus-manager for me and for other not-so-techy users who just want to install optimus-manager and everything to work as smoothly as possible.

Thank you!

**System info**
OS: Manjaro Linux x86_64 
Host: 20217 Lenovo IdeaPad Y510P 
Kernel: 5.0.5-1-MANJARO 
Resolution: 1920x1080 
DE: KDE 5.15.3-1
CPU: Intel i7-4700MQ (8) @ 3.400GHz 
GPU: Intel 4th Gen Core Processor 
GPU: NVIDIA GeForce GT 750M 
Memory: 1958MiB / 7892MiB

**Comment by cdfa** [comment] 2019-04-20 08:23
Having the same problem.

```
> inxi -CGMS
System:    Host: colin-laptop Kernel: 4.19.32-1-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.15.3
Distro: Manjaro Linux
Machine:   Type: Laptop System: HP product: HP Pavilion Gaming Notebook v: Type1ProductConfigId
serial: <root required>
Mobo: HP model: 816B v: 91.1E serial: <root required> UEFI: Insyde v: F.88 date: 06/27/2018
CPU:       Topology: Quad Core model: Intel Core i7-6700HQ bits: 64 type: MT MCP L2 cache: 6144 KiB
Speed: 800 MHz min/max: 800/3500 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 800 5: 800 6: 800
7: 800 8: 800
Graphics:  Device-1: Intel HD Graphics 530 driver: i915 v: kernel
Device-2: NVIDIA GM107M [GeForce GTX 950M] driver: nvidia v: 418.43
Display: x11 server: X.Org 1.20.4 driver: modesetting,nvidia resolution: 1920x1080~60Hz
OpenGL: renderer: GeForce GTX 950M/PCIe/SSE2 v: 4.6.0 NVIDIA 418.43
```

**Comment by xnumad** [comment] 2019-04-21 02:40
See also #26, especially the [solution comment](https://github.com/Askannz/optimus-manager/issues/26#issuecomment-450719510) that hints to the solution:
Write in `/etc/optimus-manager/optimus-manager.conf`:
```
[nvidia]
DPI=96
```
([System info](https://gist.github.com/xnumad/258cc1439f426330f23ddc1e9a356e41))

**Comment by xnumad** [comment] 2019-04-21 02:43
See also #26, especially [this comment](https://github.com/Askannz/optimus-manager/issues/26#issuecomment-450719510) that hints to another solution than the one in the first comment here:
Write in `/etc/optimus-manager/optimus-manager.conf`:
```
[nvidia]
DPI=96
```

**Comment by Socterean** [comment] 2019-04-23 19:45
> See also #26, especially [this comment](https://github.com/Askannz/optimus-manager/issues/26#issuecomment-450719510) that hints to another solution than the one in the first comment here:
> Write in `/etc/optimus-manager/optimus-manager.conf`:
> 
> ```
> [nvidia]
> DPI=96
> ```

Setting `DPI=96` in `/etc/optimus/manager/optimus-manager.conf` doesn't seem to work on my setup. But setting it directly as `Option "DPI" "96 x 96"` in `/etc/optimus-manager/xorg-nvidia.conf` does the trick.

**Comment by Askannz** [comment] 2019-05-04 07:19
The latest Git version of optimus-manager now defaults to 96 dpi for Nvidia. There are some major changes in this version, so the next time you upgrade, make sure to reboot our computer just after so that everything is reloaded up properly.

**Comment by Askannz** [comment] 2019-05-04 07:36
Closing this issue as it's a duplicate of https://github.com/Askannz/optimus-manager/issues/50.

**Closed by Askannz** 2019-05-04 07:36 UTC

**Comment by Socterean** [comment] 2019-05-04 11:07
I made an `optimus-manager --cleanup` uninstalled `optimus-manager 0.8.2` and then installed `optimus-manager-git` from the `AUR` and the problem remains the same, I get incorrect DPI until I add that line to `/etc/optimus-manager/xorg-nvidia.conf`

I want to also add that the same problem has ocured to me on other two Lenovo laptops on wich I installed Manjaro recently. So I had to add that line manually for the DPI to be set and look correct.
