### ISSUE TITLE
Multi-head does not work in integrated card

### ISSUE THREAD

**Issue by cassioalmeidas** [Askannz/optimus-manager#509] opened 2022-08-02 01:21 UTC
When I use my integrated card (HD Graphics 630), my OS does not recognize the external monitor, the external monitor is detected only when I switch to the nvidia dedicated card.

My environment: ArchLinux + XFCE + LightDM
My laptop model: Acer Nitro 5 AN515-51-78D6
I'm currently using the optimus-manager-git package, but I've already tested the optimus-manager package as well.

**Comment by lunakiller** [comment] 2022-09-05 09:15
I am afraid this is not a bug but rather a feature. Usually the HDMI or DP port on laptops is wired to the dedicated graphics card, which means that external monitors are not recognized if the card is not running. In integrated mode, the nvidia card is disabled. At least hybrid mode is required.

ENV: Manjaro + i3/Mate + LightDM
NTB: MSI GP63 Leopard 8RE-430CZ

**Comment by nwildner** [comment] 2024-07-01 12:46
Closing since this is not a bug. Lots of laptops have their HDMI or mini-DP ports hardwired to the external GPU so, in integrated setups this will not work. 

I have the very same problem with my [ASUS Tuf Dash 15](https://wiki.archlinux.org/title/ASUS_TUF_DASH_F15_(2022))(FX517ZR) and there is no much it can be done here.

**Closed** 2024-07-01 12:46 UTC
Labels: wontfix
