### ISSUE TITLE
Cannot switch to nvidia, wrongly set current mode as nvidia

### ISSUE THREAD

**Issue by slade991** [Askannz/optimus-manager#515] opened 2022-09-19 08:32 UTC
**Describe the bug**
After updating my system optimus-manager still says i'm using nvidia, but i'm not, i'm using intel and it cannot switch to nvidia anymore.

**System info**
Arch (Linux arch 5.15.68-1-lts #1 SMP Thu, 15 Sep 2022 09:53:50 +0000 x86_64 GNU/Linux) 
with gnome (GNOME Shell 42.5)

**Logs**
no error with status but here is my boot switch log :
```
[17] INFO: # Xorg pre-start hook
[17] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'nvidia', 'current_mode': None}
[17] INFO: Requested mode is: nvidia
[192] INFO: Available modules: ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[192] INFO: Unloading modules ['nouveau'] (if loaded)
[195] INFO: switching=none, nothing to do
[246] INFO: Loading module nvidia
[716] INFO: Loading module nvidia_drm
[1286] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
[1286] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20220919T152607', 'requested_mode': 'nvidia'}
[1286] INFO: Xorg pre-start hook completed successfully.
[6] INFO: # Xorg post-start hook
[6] INFO: Running xrandr commands
[576] ERROR: Cannot setup PRIME (xrandr error):
None
[576] INFO: Running /etc/optimus-manager/xsetup-nvidia.sh
[587] ERROR: Cannot set DPI (xrandr error):
None
[587] INFO: Writing state {'type': 'done', 'switch_id': '20220919T152607', 'current_mode': 'nvidia'}
[587] INFO: Xorg post-start hook completed successfully.
[7] INFO: # Xorg pre-start hook
[21] INFO: Previous state was: {'type': 'done', 'switch_id': '20220919T152607', 'current_mode': 'nvidia'}
[21] INFO: Requested mode is: nvidia
[36] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
[36] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20220919T152607', 'requested_mode': 'nvidia'}
[36] INFO: Xorg pre-start hook completed successfully.
[6] INFO: # Xorg post-start hook
[6] INFO: Running xrandr commands
[760] INFO: Running /etc/optimus-manager/xsetup-nvidia.sh
[774] INFO: Writing state {'type': 'done', 'switch_id': '20220919T152607', 'current_mode': 'nvidia'}
[774] INFO: Xorg post-start hook completed successfully.
[8] INFO: # Xorg pre-start hook
[24] INFO: RUNNING_UNDER_GDM is set and Xorg is still running. Aborting this hook because it was likely called by GDM when closing its login screen.
[7] INFO: # Xorg pre-start hook
[22] INFO: RUNNING_UNDER_GDM is set and Xorg is still running. Aborting this hook because it was likely called by GDM when closing its login screen.
[7] INFO: # Xorg pre-start hook
[24] INFO: RUNNING_UNDER_GDM is set and Xorg is still running. Aborting this hook because it was likely called by GDM when closing its login screen.
```

**Comment by slade991** [comment] 2022-10-25 02:00
Is this project still maintained ? 
It looks like most issues are not looked at.
My issue seems to be related to this one : https://github.com/Askannz/optimus-manager/issues/436
from last year which is still open. 
Let me know if more information are necessary.

**Comment by nwildner** [comment] 2024-07-01 11:48
Sup @slade991 . While it was not maintained for some time and it had a hiatus, there is a bunch of volunteers coming back to merge stuff and collaborate here.

Is this still reproducing using `optimus-manager-git` and a more modern Linux install ?

Since this issue isn't active for the last 2 years ago and a lot has changed in many aspects of multiple software, we'll keep this case opened for some days and close it if no answer is provided.

Have a nice week ahead.

**Closed** 2024-07-05 11:54 UTC
