### ISSUE TITLE
Switching to Nvidia and screen goes black.

### ISSUE THREAD

**Issue by AciDev** [Askannz/optimus-manager#113] opened 2019-08-08 20:07 UTC
Hey there,

Ive been trying to set up optimus manager for the past few days and although i got through a few hurdles I am stuck on this and cant really figure our where to go next.

Thanks for any help you can give me.
[Xorg.0.log](https://github.com/Askannz/optimus-manager/files/3483474/Xorg.0.log)
[Xorg.8.log](https://github.com/Askannz/optimus-manager/files/3483475/Xorg.8.log)
[boot_setup.log](https://github.com/Askannz/optimus-manager/files/3483478/boot_setup.log)
[gpu_setup.log](https://github.com/Askannz/optimus-manager/files/3483479/gpu_setup.log)
[prime_setup.log](https://github.com/Askannz/optimus-manager/files/3483480/prime_setup.log)

**Comment by chabad360** [comment] 2019-08-09 01:47
Are you using GDM?

**Comment by AciDev** [comment] 2019-08-09 06:24
Hi totally forgot to say I'm on KDE Manjaro on a thinkpad x1 extreme

**Comment by chabad360** [comment] 2019-08-10 01:21
I don't know if this will help, but try switching your TTY (the shortcut
should be Ctrl+Alt+F2 or F3 or FRIDAY, etc.)

**Comment by AciDev** [comment] 2019-08-10 10:24
Yeah I can switch to the TTY just cant boot into nvidia mode

**Comment by rockyprabowo** [comment] 2019-08-10 15:27
Maybe this was caused by Nouveau failing to switch on/off the dGPU. Nouveau is literally unusable with GPU with Pascal or newer architecture. You might want to change the power switching backend to `none` or `bbswitch` (if `bbswitch` somehow works on your machine) in the configuration file (section `[optimus]`, parameter switching)
Read the FAQ for more information: https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#after-trying-to-switch-gpus-i-am-stuck-with-a-black-screen-or-a-black-screen-with-a-blinking-cursor-or-a-tty-login-screen

**Comment by Ghakizu** [comment] 2019-08-10 19:39
I have the same problem even if I apply all the fix from the FAQ
Should I open a new issue ?

**Comment by cyberactive** [comment] 2019-08-13 23:42
Same issue. This is also with a Thinkpad X1 Extreme. Could be model specific issue?

**Comment by Askannz** [comment] 2019-08-14 23:27
@AciDev what are the symptoms exactly ? What happens when you try to switch to nvidia or boot into nvidia mode ?

Also, did you follow the special instructions for Manjaro KDE ? https://github.com/Askannz/optimus-manager#installation

**Comment by Ghakizu** [comment] 2019-08-15 13:56
@cyberactive I got this issue with a hp omen
I don't think it is model specific

**Comment by Ghakizu** [comment] 2019-08-21 19:58
I just added `xrandr --auto` in my ~/.xprofile and now it works for me

**Comment by gbytedev** [comment] 2019-08-24 21:15
@AciDev You have the same setup as me (Manjaro + X1 Extreme), please check out the [Arch wiki](https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X1_Extreme), where I just added a section regarding optimus-manager. The setup is working well on my Arch and Manjaro boxes; feel free to ask.

**Comment by gruel** [comment] 2019-09-02 19:48
I have the same laptop, Thinkpad X1 extreme, and I got the same problem. I tried the solution from the arch wiki but I still have the black screen on the laptop screen but the three output are working as expected.

**Comment by Askannz** [comment] 2019-10-20 02:14
Is this still an issue with the latest version of optimus-manager ?

**Comment by gruel** [comment] 2019-10-20 19:26
Seems to work on my system. I still have a login black loin screen when not connected to a second screen but I am suspecting that the problem is due to sddm not optimus-manager. Thanks.

**Comment by chabad360** [comment] 2019-10-20 20:37
> Is this still an issue with the latest version of optimus-manager ?

Yup, it appears to still be an issue on my system...

**Comment by tojestzart** [comment] 2020-01-08 16:10
its heavy bug under nvidia driver itself, on nvidia dev forum i have been silenced, on launchpad i have incomplete bug report, following https://forum.manjaro.org/t/guide-install-and-configure-optimus-manager-for-hybrid-gpu-setups-intel-nvidia/92196 gives exactly same result on all distros which i have tested, debian, kubuntu, mint, manjaro 
REPRODUCE: 
1) follow tutorial from manjaro forum
2) switch to nvidia 
3) play some game, close it
4) press suspend to ram under KDE
5) screen hangs

**Comment by Askannz** [comment] 2020-03-05 23:54
@tojestzart Suspend has always been broken on Nvidia, it causes all kinds of weird behavior. It's not an optimus-manager bug, and there isn't anything I can do about it.

@chabad360 if you are still experiencing this issue, can you provide system info and logs ?

**Comment by beams3sge** [comment] 2020-04-25 22:18
hello 
i have the same issue 'black screen after changing to nvidia and the only thing are works are the cairo-dock and the yakuake'
my optimus manager's version is 1.22 and my logs are:
[Xorg.0.log](https://github.com/Askannz/optimus-manager/files/4534188/Xorg.0.log)
[boot_setup.log](https://github.com/Askannz/optimus-manager/files/4534189/boot_setup.log)
[gpu_setup.log](https://github.com/Askannz/optimus-manager/files/4534190/gpu_setup.log)
[prime_setup.log](https://github.com/Askannz/optimus-manager/files/4534192/prime_setup.log)
I'm on Manjaro KDE with PLASMA ver: 5.18.4
KDE Framework 5.69.0 
qt 5.14.2
5.6.6-1 manjaro kernel 
my os is 64bit
the laptop is an DELL XPS l502x 8gb ram  and geforce gt540m.
Thanks a lot

**Comment by nwildner** [comment] 2024-07-01 16:20
Since this is a longstanding issue here and the last activity seems to be from 4 years ago, please track the case #552 here.

Also, for those who are still using optimus-manager, stick with `optimus-manager-git` package since a lot of recent PRs got merged. 

Cheers.

**Closed by nwildner** 2024-07-01 16:20 UTC
Labels: bug

**Comment by I-dont-need-name** [comment] 2024-07-01 23:32
Can confirm having a similar issue on Manjaro, might be after update to driver 555, but I'm not sure (Everything used to work properly on my setup some time ago).

**Comment by nwildner** [comment] 2024-07-02 08:19
Sup @I-dont-need-name . Could you please report on #552 , and provide any logs you might have after the issue happened and the usual information (laptop model, CPU, GPU, Distribution, Nvidia driver version, Kernel version)...
Cheers.
