### ISSUE TITLE
[Question] PCI-Express Runtime D3 (RTD3) Power Management

### ISSUE THREAD

**Issue by mindrunner** [Askannz/optimus-manager#313] opened 2020-08-26 14:08 UTC
**Describe the bug**
Probably not a bug. I am on a DELL Precision 5750 (very same than XPS 17), latest Arch, Zen Kernel, i3wm, optimus-manager hybrid mode. I am driving two displays via DELL WD19TB Dock, attached to the Intel GPU. Everything seems to work fine so far, including using NVidia with Steam (offload the rendering).

However, I am not quite sure if the NVidia card proper shuts down when not in use. I followed all steps in 
https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/dynamicpowermanagement.html

nvidia-smi shows me mostly something around 3W usage (P8), but sometimes more (~18W) (P0). Xorg is constantly listed as a process, even though nothing is running on GPU.
```
[le@p5750]: ~>$ nvidia-smi 
Wed Aug 26 16:06:59 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.66       Driver Version: 450.66       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 3000...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   46C    P0    18W /  N/A |      6MiB /  5934MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3511      G   /usr/lib/Xorg                       4MiB |
+-----------------------------------------------------------------------------+
```

**Logs**
```
[le@p5750]: ~>$ optimus-manager --status

Optimus Manager (Client) version 1.3

Current GPU mode : hybrid
GPU mode requested for next login : no change
GPU at startup : hybrid
Temporary config path: no
```

```
[optimus]

# This parameter defines the method used to power switch the Nvidia card. See the documentation
# for a complete description of what each value does. Possible values :
#
# - nouveau : load the nouveau module on the Nvidia card.
# - bbswitch : power off the card using the bbswitch module (requires the bbswitch dependency).
# - acpi_call : try various ACPI method calls to power the card on and off (requires the acpi_call dependency)
# - none : do not use an external module for power management. For some laptop models it's preferable to
#           use this option in combination with pci_power_control (see below).
#switching=bbswitch

# Enable PCI power management in Intel mode.
# This option is incompatible with acpi_call and bbswitch, so it will be ignored in those cases.
pci_power_control=no

# Reset the Nvidia card at the PCI level before reloading the nvidia module.
# May fix some switching issues but also cause instability.
pci_reset=no

# Remove the Nvidia card from the PCI bus before powering off.
# May prevent crashes caused by power switching.
pci_remove=no

# Automatically log out the current desktop session when switching GPUs.
# This feature is currently supported for the following DE/WM :
# KDE Plasma, GNOME, XFCE, Deepin, i3, Openbox
# If this option is disabled or you use a different desktop environment,
# GPU switching only becomes effective at the next graphical session login.
auto_logout=yes

# GPU mode to use at computer startup. Possible values: nvidia, intel, hybrid, auto
# "auto" is a special mode that auto-detects if the computer is running on battery
# and selects a proper GPU mode. See the other options below.
startup_mode=hybrid
# GPU mode to select when startup_mode=auto and the computer is running on battery.
# Possible values: nvidia, intel, hybrid
startup_auto_battery_mode=hybrid
# GPU mode to select when startup_mode=auto and the computer is running on external power.
# Possible values: nvidia, intel, hybrid
startup_auto_extpower_mode=hybrid


[intel]

# Driver to use for the Intel GPU. Possible values : modesetting, intel
# To use the intel driver, you need to install the package "xf86-video-intel".
driver=modesetting

# Acceleration method (corresponds to AccelMethod in the Xorg configuration).
# Only applies to the intel driver.
# Possible values : sna, xna
# Leave blank for the default (no option specified)
#accel=sna

# Enable TearFree option in the Xorg configuration.
# Only applies to the intel driver.
# Possible values : yes, no
# Leave blank for the default (no option specified)
#tearfree=yes

# DRI version. Possible values : 2, 3
DRI=3

# Whether or not to enable modesetting for the nouveau driver.
# Does not affect modesetting for the Intel GPU driver !
# This option only matters if you use nouveau as the switching backend.
#modeset=yes

[nvidia]

# Whether or not to enable modesetting. Required for PRIME Synchronization (which prevents tearing).
modeset=yes

# Whether or not to enable the NVreg_UsePageAttributeTable option in the Nvidia driver.
# Recommended, can cause poor CPU performance otherwise.
PAT=yes

# DPI value. This will be set using the Xsetup script passed to your login manager.
# It will run the command
# xrandr --dpi <DPI>
# Leave blank for the default (the above command will not be run).
DPI=96


# Comma-separated list of Nvidia-specific options to apply.
# Available options :
# - overclocking : enable CoolBits in the Xorg configuration, which unlocks clocking options
#   in the Nvidia control panel.
# - triple_buffer : enable triple buffering.
options=overclocking,triple_buffer
```

Any thoughts?

**Comment by ttsesm** [comment] 2020-09-10 20:18
@mindrunner I am on the same boat. Same exactly issue, only difference is that I not using optimus manager anymore since it seems that with the new nvidia driver output sinking which was my main problem is resolved. 

Another issue that I am facing and it might be related is that I cannot manage to have audio hdmi pass-through when I connect an external screen with speakers. Checking on the wiki I found that most likely I am falling within [this section](https://wiki.archlinux.org/index.php/NVIDIA/Troubleshooting#No_audio_over_HDMI) but when I try to remove the nvidia modules I am getting the error that they are in use, which tells me that my dGPU is active.

In the nvidia upstream documentation for the [latest driver ](https://us.download.nvidia.com/XFree86/Linux-x86_64/450.57/README/dynamicpowermanagement.html) there is a part that it explicitly mentions that:

```
Furthermore, the NVIDIA GPU driver controls power to the NVIDIA GPU and its video memory separately. While turning off the NVIDIA GPU, the video memory will be kept in a low power self-refresh mode unless the following conditions are met:

    The system is configured in PRIME render offload mode. See Chapter 34, PRIME Render Offload for details.
```

Which as I understand it while I am in PRIME render offload mode the dGPU is not turned off. I do know whether I interpret it correctly though.

I've [opened an thread](https://bbs.archlinux.org/viewtopic.php?pid=1925464#p1925464) in the arch forum but so far not response.

Let me know if you figured out anything.

**Comment by mindrunner** [comment] 2020-09-10 20:57
Well, the only thing I figure out almost every day is, that NVIDIA really sucks from the perspective of a Linux user. :(

I migrated mi i3 to sway (wayland) and then figured out, that using the NVIDIA card over here is entirely impossible, because.... well because everyone blames the others and no one feels responsible. 


Ok, one more thing I can add here. Now, there are no processes at all running on the card and it still consumes some power. (which it is not supposed to do)



![image](https://user-images.githubusercontent.com/1413542/92804841-3cd14d00-f37e-11ea-8e40-2d6c2c4334d3.png)

**Comment by ttsesm** [comment] 2020-09-10 21:35
No in my case it clearly in use:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.66       Driver Version: 450.66       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   44C    P0    17W /  N/A |      6MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1610      G   /usr/lib/Xorg                       4MiB |
+-----------------------------------------------------------------------------+
```
Similarly to your initial message.

**Comment by mindrunner** [comment] 2020-09-10 21:45
It sometimes looks similar here when issuing a single call to `nvidia-smi`. What happens of you do a `watch nvidia-smi`? Does it stay with such a high wattage? Is that an XPS17 btw?

**Comment by ttsesm** [comment] 2020-09-10 22:35
With `watch nvidia-smi` I can see that it also drops down to 7W.

Nope, it is a blade 15 with i7-10875H/RTX2080. The setup should be similar to yours though, i.e. laptop screen on intel, hdmi/DP hard wired to nvidia.

**Comment by ttsesm** [comment] 2020-09-10 23:11
I also found the following thread https://bbs.archlinux.org/viewtopic.php?id=243402
I do not know whether it can help but I will give it a try tomorrow.

**Comment by ttsesm** [comment] 2020-09-11 07:37
Btw, is audio hdmi pass-through working in your case? Have you tried it.

**Comment by mindrunner** [comment] 2020-09-11 07:50
> With `watch nvidia-smi` I can see that it also drops down to 7W.
> 
> Nope, it is a blade 15 with i7-10875H/RTX2080. The setup should be similar to yours though, i.e. laptop screen on intel, hdmi/DP hard wired to NVIDIA.

One of the reasons I turned my back to lenovo and going back to DELL is they do not hard-wire the digital outs to the nvidia card. So, my setup is different. I do not rely on nvidia connecting external screens and can run purely on intel if I want to. Good to know, Razer has similar issues. No idea why they do it, but it locks out several use cases (at least on linux OS)

> Btw, is audio HDMI pass-through working in your case? Have you tried it.

The new DELL series has very cutting edge audio hardware. Drivers are not upstream yet and some manual steps are required. I managed to get the HDMI audio work (probably not NVIDIA, though), but not the internal speakers. I am mainly docked to a WD19TB (which is crap imho) and using its usb-audio device which works out of the box.

**Comment by ttsesm** [comment] 2020-09-11 09:25
I see, thanks for the feedback. Well nvidia graphics and closed drivers though there are some improvements lately, still it is a bit of pain to make it work properly (if ever). Anyways lets see, I will continue looking around in case I can find some workaround.

**Comment by Askannz** [comment] 2020-09-20 01:24
So, uh, turns out there WAS a bug in optimus-manager regarding power management. The PCI power control was set to "on" even in hybrid mode, which I suppose would prevent the card from going to sleep.

Please try with the latest master version (use `optimus-manager-git`). Make sure that `pci_power_control` is set to `yes` in the config file.

**Comment by ttsesm** [comment] 2020-09-20 17:12
@Askannz in a new laptop with nvidia card >20xx is the optimus-manager in the hybrid mode offering anything extra other than what you can get by the default PRIME offloading setup (based on the archwiki) now that the nvidia driver support output sinking?

**Comment by mindrunner** [comment] 2020-09-21 16:52
I figured out that my card seems to shut down actually, but calling `nvidia-smi` wakes it up. On a sleeping card, the call to `nvidia-smi` blocks for a second or so before actually showing the stats. Subsequent calls will immediately return information. This lets me assume, the card is working fine. I could not find a way to check for the sleep state without waking up the card, however.

**Comment by mindrunner** [comment] 2020-09-21 17:00
> Make sure that `pci_power_control` is set to `yes` in the config file.

Should't be all software power control turned of on modern cards, because the driver will shut them down as soon as they are not needed?

**Comment by nwildner** [comment] 2024-07-03 08:51
Sup folks.

This is an old discussion regarding RTD3 Power Management and since the last update was from 4 years ago, I'll be closing this. 
Feel free to reopen if you think is a bug and not an expected behavior generated by `nvidia-smi`  waking up the GPU again to provide output data. We're trying to keep Github issues clean here to put this project back on full traction.

Have a nice day.

**Closed by nwildner** 2024-07-03 08:51 UTC

**Comment by mindrunner** [comment] 2024-07-03 10:50
Personally, I moved on by using nvidias native approach, removing the dependency to optimus-manager at all. But imo the original problem was not at all related to optimus-manager anyways. `nvidia-smi` is supposed to wake up the GPU, hence not an option to determine whether it is sleeping or not.

Just for reference, one could do something like:

```
#!/bin/bash

# Check if nvidia-smi and jq are available
command -v nvidia-smi >/dev/null 2>&1 || { echo >&2 "nvidia-smi is required but it's not installed. Aborting."; exit 1; }
command -v jq >/dev/null 2>&1 || { echo >&2 "jq is required but it's not installed. Aborting."; exit 1; }

status=$(cat /sys/bus/pci/devices/0000\:01\:00.0/power/runtime_status 2>/dev/null)

# Check if the cat command was successful
if [ $? -ne 0 ]; then
    echo >&2 "Failed to read runtime_status. Aborting.";
    exit 1;
fi

alt=""
tooltip=""
class=$status
percentage='0'

case "$status" in
    *suspended*)
        text=""
        ;;
    *active*)
        # Capture nvidia-smi output to a variable
        nvidia_output=$(nvidia-smi dmon -s pu -c 1 2>&1)
        error_code=$?

        if [ $error_code -eq 18 ]; then
            text="N/A"
        else
            wattage=$(echo "$nvidia_output" | grep -v "#" | awk '{print $2}')
            temp=$(echo "$nvidia_output" | grep -v "#" | awk '{print $3}')
            percentage=$(echo "$nvidia_output" | grep -v "#" | awk '{print $4}')
            text="$temp°C / ${wattage}W"
        fi
        ;;
esac

tooltip=$text
alt=$text

JSON_STRING=$( jq -n \
                  --arg text "$text" \
                  --arg alt "$alt" \
                  --arg tooltip "$tooltip" \
                  --arg class "$class" \
                  --arg percentage "$percentage" \
                  '{text: $text, alt: $alt, tooltip: $tooltip, class: $class, percentage: $percentage}' )

echo $JSON_STRING

```

NVIDIA is still shit and there is way too many issues with Linux. Every driver upgrade breaks something else. Power Management on laptops is a hit and miss. Try to avoid it as much as you can.
