### ISSUE TITLE
Run Xorg using Intel graphics in hybrid mode (Manjaro KDE)

### ISSUE THREAD

**Issue by yenson-lau** [Askannz/optimus-manager#275] opened 2020-06-18 05:35 UTC
When I run `nvidia-smi`, I get the following output:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 165...  Off  | 00000000:58:00.0 Off |                  N/A |
| N/A   45C    P8     1W /  N/A |     55MiB /  3911MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1150      G   /usr/lib/Xorg                                 54MiB |
+-----------------------------------------------------------------------------+
WARNING: infoROM is corrupted at gpu 0000:58:00.0
```
I'd really like to shave off the last few watts of GPU usage on idle if possible, since the Intel GPU is completely capable of running Xorg. Is there any way of doing this or is it technically not possible? Maybe this is explained in the README already... if that's the case I apologize in advance.

*Aside*: I'm wondering if `WARNING: infoROM is corrupted at gpu 0000:58:00.0` is a problem? Also sorry if I'm not using the right channels to ask the question!

**Comment by nariox** [comment] 2020-06-19 14:15
Power management is only fully supported on Coffee Lake+ and Turing+. If your system belongs to this group, you can follow these instructions: https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/dynamicpowermanagement.html

Otherwise you are stuck with using Intel only or Hybrid with the GPU going down to P8 at most. Alternatively, you could use bumblebee, but at a(n arguably) significant overhead.

infoROM is a proprietary internal memory region. The driver uses some kind of checksum on it, if the checksum fails, it will give you this message. It is possible your GPU is busted, but more likely, this is a harmless warning.

**Comment by yenson-lau** [comment] 2020-06-19 14:44
Thanks for the reply @nariox, I have already followed all the instructions on the README and my system is indeed Coffee Lake+ but my graphics card is a GTX 1650Ti, so it doesn't seem to be Turing+. Does this mean that it's not possible for Xorg to run on Intel in hybrid mode?

**Comment by nariox** [comment] 2020-06-19 15:24
I think the 1650Ti is Turing, but NVIDIA has been really confusing on these generations (like the 750Ti being Maxwell).

On hybrid mode, everything runs on Intel, but you run an additional Xorg session on NVidia. This is how NVidia implemented PRIME offloading. But you might be able to suspend it by following the instructions on the link I have sent. In hybrid mode, everything is run in the iGPU, unless you call the command using the `__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia` environment variables.


By the way, `nvidia-smi` wakes the GPU up, so it will not show you if your GPU is suspending. You can see it with this (adjust to the correct PCI bus if it doesn't work):

    tail -n 1  /sys/bus/pci/devices/0000\:01\:00.0/power/*

**Comment by yenson-lau** [comment] 2020-06-19 15:45
Hmm... the output I posted was actually after enabling the settings from your link, and the Xorg process still shows up, so I guess that's a no go.

Those settings have also been causing a lot of erratic behaviour on my laptop (randomly suspends when running intense applications). Both the infoROM issue and the erratic behaviour disappears after undoing them.

**Comment by nariox** [comment] 2020-06-19 17:06
The Xorg process will be there regardless.

In the command I have sent (some of them I am assuming, since my machine is KBL), you should have: `control = auto` `runtime_status = suspended` (when non running anything)  and `runtime_suspended_time` should be non-zero.

Also, make sure your runtime_pm is enabled (TLP disables it for NVidia by default). You can check it with `powertop`.

**Comment by yenson-lau** [comment] 2020-06-19 18:20
Hmm... I have `control = on`, `runtime_status = active` and `runtime_suspended_time = 0`. My runtime_pm seems to be off for some NVIDIA devices. Do you know how I can turn these on?

**Comment by nariox** [comment] 2020-06-19 18:40
Do you use TLP? If not, you can just use `powertop`. Otherwise, you can
configure it in TLP.

**Comment by yenson-lau** [comment] 2020-06-19 18:42
I looked in `/etc/tlp.conf` and no such option seems to exist. Do you know if powertop configurations are persistent?

**Comment by yenson-lau** [comment] 2020-06-19 19:14
I've removed `nvidia` from the `RUNTIME_PM_BLACKLIST`, so that `RUNTIME_PM_ON_BAT=auto` for the NVIDIA card. Running the laptop on battery and enabling the [the NVIDIA settings](https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/dynamicpowermanagement.html), I do indeed see that `control = auto` `runtime_status = suspended` and `runtime_suspended_time` is non-zero. I've also disabled the `nouveau drivers`

Unfortunately, the issues that show up whenever I enable the NVIDIA settings have never gone away, regardless of what combination of options I enable. Specifically:
1. `WARNING: infoROM is corrupted at gpu 0000:58:00.0` displayed on `nvidia-smi`
2. Shutdown of the laptop freezes (always requires a hard shutdown with power button)
3. Laptop goes into suspend sporadically when running intense applications

I might keep tinkering to see whether this can be fixed, but if not I can always just switch to `intel` mode whenever I take the laptop outside... it's not the end of the world.

**Comment by nariox** [comment] 2020-06-19 19:29
Yeah, NVIDIA says this feature is "highly experimental", which I think it
means "will cause issues, don't complain". Optimus-manager has a "auto"
mode, which enables intel-only if you boot on battery. I'm just as
frustrated as Optimus was launched in 2011, but somehow my Kaby Lake
R/Pascal laptop is "too old" to support proper power management.

**Comment by Tmpod** [comment] 2020-10-28 10:25
> The Xorg process will be there regardless.
> 
> In the command I have sent (some of them I am assuming, since my machine is KBL), you should have: `control = auto` `runtime_status = suspended` (when non running anything) and `runtime_suspended_time` should be non-zero.
> 
> Also, make sure your runtime_pm is enabled (TLP disables it for NVidia by default). You can check it with `powertop`.

I have the exact same issue, and for me `runtime_status` is `active`, but then `runtime_suspended_time` it non-zero... Any ideas?

I'm running an i7-9750H and a GTC 1660Ti, so they are both supposedely capable of using the dynamic power management thing. I've also followed the nvidia guide of course.

Thanks in advance :)

**Comment by nariox** [comment] 2020-10-28 14:13
Can you post your `tail -n 1  /sys/bus/pci/devices/0000\:01\:00.0/power/*`?

**Comment by Tmpod** [comment] 2020-10-29 19:17
Of course!

`tail -n 1 /sys/bus/pci/devices/0000\:01\:00.0/power/*`
```
==> /sys/bus/pci/devices/0000:01:00.0/power/async <==
enabled

==> /sys/bus/pci/devices/0000:01:00.0/power/autosuspend_delay_ms <==
tail: error reading '/sys/bus/pci/devices/0000:01:00.0/power/autosuspend_delay_ms': Input/output error

==> /sys/bus/pci/devices/0000:01:00.0/power/control <==
auto

==> /sys/bus/pci/devices/0000:01:00.0/power/runtime_active_kids <==
0

==> /sys/bus/pci/devices/0000:01:00.0/power/runtime_active_time <==
60787870

==> /sys/bus/pci/devices/0000:01:00.0/power/runtime_enabled <==
enabled

==> /sys/bus/pci/devices/0000:01:00.0/power/runtime_status <==
active

==> /sys/bus/pci/devices/0000:01:00.0/power/runtime_suspended_time <==
1309

==> /sys/bus/pci/devices/0000:01:00.0/power/runtime_usage <==
1

==> /sys/bus/pci/devices/0000:01:00.0/power/wakeup <==
disabled

==> /sys/bus/pci/devices/0000:01:00.0/power/wakeup_abort_count <==


==> /sys/bus/pci/devices/0000:01:00.0/power/wakeup_active <==


==> /sys/bus/pci/devices/0000:01:00.0/power/wakeup_active_count <==


==> /sys/bus/pci/devices/0000:01:00.0/power/wakeup_count <==


==> /sys/bus/pci/devices/0000:01:00.0/power/wakeup_expire_count <==


==> /sys/bus/pci/devices/0000:01:00.0/power/wakeup_last_time_ms <==


==> /sys/bus/pci/devices/0000:01:00.0/power/wakeup_max_time_ms <==


==> /sys/bus/pci/devices/0000:01:00.0/power/wakeup_prevent_sleep_time_ms <==


==> /sys/bus/pci/devices/0000:01:00.0/power/wakeup_total_time_ms <==
```

Assuming those time numbers are milliseconds, it seems the GPU wasn't suspended more than 1 second, possibly the time before Xorg was started?

**Comment by Tmpod** [comment] 2020-12-14 19:22
Sorry to bump this, but it's quite a limiting thing for me since it reduces de battery life in 2/3h... Anyone has any idea why Xorg is keeping the dGPU busy?

Thanks in advance.

**Comment by nariox** [comment] 2020-12-14 20:15
Sorry, seems like this slipped through the cracks.

DId you add `options nvidia "NVreg_DynamicPowerManagement=0x01"` (or `0x02`) to a modprobe.d file (e.g. `/etc/modprobe.d/nvidia.conf`)?

**Comment by Tmpod** [comment] 2020-12-15 16:03
> Sorry, seems like this slipped through the cracks.

No problem :p

> DId you add `options nvidia "NVreg_DynamicPowerManagement=0x01"` (or `0x02`) to a modprobe.d file (e.g. `/etc/modprobe.d/nvidia.conf`)?

Yep.

**Comment by nariox** [comment] 2020-12-15 18:32
What does `# optimus-manager --status` say?

**Comment by Tmpod** [comment] 2020-12-17 23:34
Sorry for the delaye reply, seems like I missed the notification.
Anyways, `optimus-manager` properly shows the mode, as well as the gtk tray icon.

**Comment by nariox** [comment] 2020-12-17 23:41
What about `$ cat /proc/driver/nvidia/gpus/*/power`?

**Comment by Tmpod** [comment] 2020-12-19 12:15
It shows
```
Runtime D3 status:          Enabled (fine-grained)
Video Memory:               Active

GPU Hardware Support:
 Video Memory Self Refresh: Supported
 Video Memory Off:          Supported
```

I also noticed something weird now. I seem to be unable to switch modes on the fly. If I switch then logout and log back in, it will stay on the previous mode and `--print-mode` will say the switch is pending... Not sure what's going on here. The only way to actually switch modes is to reboot the computer and change the default mode.

**Comment by nariox** [comment] 2020-12-19 13:49
It seems like your RTD3 is working as intended. The power consumption is
probably something else.

What DM are you using? This might have to do with it. For example, GDM
needs a few patches to work properly.

**Comment by Tmpod** [comment] 2020-12-19 14:59
I'm using SDDM (I use Manjaro with KDE Plasma) and I have followed the [https://github.com/Askannz/optimus-manager#important--manjaro-kde-users] described in the README.

**Comment by nariox** [comment] 2020-12-19 17:36
I would file this as a different issue. Seems unrelated to this bug. Since
Manjaro overwrites files, it's possible that the modifications you did were
overwritten already, so you might want to check that out as well.

**Comment by nwildner** [comment] 2024-08-27 09:37
@yenson-lau are you stil facing this issue?

Since the last update on this case was from 3 years ago, we'll keep this case opened for some days and close it if no answer is provided.

Have a nice week ahead.

**Comment by yenson-lau** [comment] 2024-08-27 15:59
Hi @nwildner , I no longer use this system, so feel free to close the issue

**Closed** 2024-08-29 08:23 UTC
