### ISSUE TITLE
black desktop when changing from intel to nvidia

### ISSUE THREAD

**Issue by daviddoji** [Askannz/optimus-manager#237] opened 2020-04-04 16:03 UTC
**Describe the bug**
When changing from intel to nvidia, after I log in, the desktop crashes. For one second I can see the desktop, but suddenly everything goes black. I can run applications such as konsole and browser but the app launcher and the panels dissapear (black screen). I can see the mouse pointer, though. 

As the laptop seems to be fully functional, coming back to intel mode the desktop displays again successfully.

**System info**
Please include :
- Archlinux
- Plasma
- SDDM
- Dell XPS 15 (L502x)
- Latest stable release (optimus-manager)

**Logs**

[boot_setup.txt](https://github.com/Askannz/optimus-manager/files/4431864/boot_setup.txt)
[gpu_setup.txt](https://github.com/Askannz/optimus-manager/files/4431865/gpu_setup.txt)
[prime_setup.txt](https://github.com/Askannz/optimus-manager/files/4431866/prime_setup.txt)
[ssdm.service.txt](https://github.com/Askannz/optimus-manager/files/4431895/ssdm.service.txt)

**Comment by Askannz** [comment] 2020-06-07 01:07
Late reply, but you should try again with v1.3. If the problem still happens, run `optimus-manager --status` and see if there's any log attached.

**Comment by daviddoji** [comment] 2020-06-13 16:55
Thanks for the reply. 
I updated to v1.3 and the problem still persists. The output you requested is the following:

`
❯ optimus-manager --status
Config parsing : error in option "dpi" in section [nvidia] : non-blank integer value required

Optimus Manager (Client) version 1.3

Current GPU mode : intel
GPU mode requested for next login : no change
GPU at startup : intel
Temporary config path: no
`

**Comment by Askannz** [comment] 2020-07-05 06:20
Just to confirm, is that the output of `optimus-manager --status` after a switch to Nvidia ? Or just from Intel mode ?

**Comment by palaboy** [comment] 2021-08-10 08:25
Happen to me also first i can switch to nvidia without a problem on KDE then after switching to integrated then go back to nvidia i got see my wallpaper then suddenly black screen with mouse cursor only, i try different Arch base distro same result,  i just fix it using external monitor because the other desktop display is there from external display i just adjust the display through system settings  "Display and Monitor" you can open that through terminal type systemsettings5 goodluck.

**Comment by nwildner** [comment] 2024-07-02 11:17
Sup folks.

This is one of the lingering cases with more than 4 years of life, and some of the issues originally reported here might not be reproducing anymore. We highly recommend you to use `optimus-manager-git` package and updated Kernel, Distibution and Nvidia driver versions.

For this case in particular, please track the following case which has the same symptoms and a more recent report regarding this matter:

- #552 -  When I switch to Nvidia, the built-in screen of the laptop stays black but I can still input my password or use monitors plugged to a video output.

This case will be closed as a duplicate but, feel free to collaborate on that newer case if this issue is still persisting.

Have a nice week.

**Closed by nwildner** 2024-07-02 11:17 UTC
Labels: bug
