### ISSUE TITLE
No shell when switching to nVidia

### ISSUE THREAD

**Issue by bphd** [Askannz/optimus-manager#340] opened 2020-11-09 11:26 UTC
PlasmaShell launch automatically on Intel but not on nVidia session opening
Which is kind of annoying

**Comment by StarGazerM** [comment] 2020-11-20 19:13
same.....I have to restart plasma by hand .
running manjaro 20 with KDE 5.76, Plasma5.20.3

**Comment by bphd** [comment] 2020-11-21 09:11
My workaround is to set a key shortcut/binding to `killall plasmashell; plasmashell` for the time when even Yakuake is not opened at the session reload and that we're basically stuck

We're waiting for a solution

**Comment by Askannz** [comment] 2020-12-12 07:37
Closing as a duplicate of https://github.com/Askannz/optimus-manager/issues/267 (and probably https://github.com/Askannz/optimus-manager/issues/289). Unfortunately I can't reproduce this issue yet.

**Closed by Askannz** 2020-12-12 07:37 UTC
