### ISSUE TITLE
Optimus-manager doesn't logout automatically and print an error on switch

### ISSUE THREAD

**Issue by JeffLabonte** [Askannz/optimus-manager#76] opened 2019-05-15 02:42 UTC
**Describe the bug**
There is an error that is printed when switching GPU. The switch happens when I logout manually and works well nevertheless

```
You are about to switch GPUs. This will forcibly close all graphical sessions and all your applications WILL CLOSE.
(you can pass the --no-confirm option to disable this warning)
Continue ? (y/N)
> y
Switching to mode : intel
Logging out the current desktop session
Traceback (most recent call last):
  File "/usr/bin/optimus-manager", line 11, in <module>
    load_entry_point('optimus-manager==1.0', 'console_scripts', 'optimus-manager')()
  File "/usr/lib/python3.7/site-packages/optimus_manager/optimus_manager_client.py", line 87, in main
    gpu_switch(config, switch_mode)
  File "/usr/lib/python3.7/site-packages/optimus_manager/optimus_manager_client.py", line 113, in gpu_switch
    sessions.logout_current_desktop_session()
  File "/usr/lib/python3.7/site-packages/optimus_manager/sessions.py", line 12, in logout_current_desktop_session
    session_bus = dbus.SessionBus()
  File "/usr/lib/python3.7/site-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python3.7/site-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.BadAddress: Server address of type unix was missing argument path or abstract
````

**System info**
Please include :
- ArchLinux
- i3
- sddm

**Logs**
[boot-setup.log](https://pastebin.com/mQcUDbd8 )
[gpu_setup.log](https://pastebin.com/mu4LXKW1)
[prime_setup.log](https://pastebin.com/RjKEfxN9l)

** EDIT: The issue #74 is most likely the same issue that I have **

**Comment by Askannz** [comment] 2019-05-16 06:32
v1.0 does not restart the display manager anymore, and instead logs the user out using DBus commands. Unfortunately those commands are DE-specific, and only Gnome, KDE or XFCE are supported for now. I have no idea if a similar command exists for i3 but I'll do some research.

That said, even if no supported DE is running, that shouldn't crash the client. So that exception is indeed a bug. Is DBus available and running on your system ?

**Comment by JeffLabonte** [comment] 2019-05-19 15:37
yes, it is.

https://pastebin.com/9VcfYXym

**Comment by JeffLabonte** [comment] 2019-05-19 15:59
I will have a look on the problem and find the right way to logout with i3 using your script! I might do a PR to give more information or a function that will handle this case!

**Comment by JeffLabonte** [comment] 2019-05-21 01:58
it seems that there is another way to handle logout that is more universal : https://unix.stackexchange.com/questions/291922/universal-way-to-logout-from-terminal-via-dbus/292048#292048

**Comment by JeffLabonte** [comment] 2019-05-21 02:23
@Askannz, I have noticed a problem with the dbus library itself when you try to run a script with dbus as root.

Consider this script as an example: https://pastebin.com/DUHQtTgN

Running as regular user: https://pastebin.com/k7eJaD7T

Running the script as root: https://pastebin.com/R5Sa9ZGL

So the error stack seems to be something unrelated to your source code but with dbus itself, although it doesn't solve the issue, I believe it narrows down the possibilities of error!

**Comment by Askannz** [comment] 2019-05-21 06:06
> it seems that there is another way to handle logout that is more universal : https://unix.stackexchange.com/questions/291922/universal-way-to-logout-from-terminal-via-dbus/292048#292048

Unfortunately no, I've tried that method before and it's actually *not* equivalent to a manual logout. It basically kills all programs indiscriminately, which messes with some session processes. In my case, it spawns some errors in the SDDM logs.

I can reproduce the same DBus error by running your script as root, but I don't think it's related. It makes sense that DBus cannot find a user bus when running as root, so that's probably not a bug.

I suspect your original issue has more to do with i3 not specifying the current user bus to the user processes. Can you try setting `DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/<uid>/bus` then running the `optimus-manager` client ? (you can find out your `uid` with `id -u`).

**Comment by minh2134** [comment] 2019-05-24 14:44
From what I gather, the only way to log out i3 DE is to actually ends the i3 session, which is equivalent to ends the X session. 

The command I found in the i3 config for exiting it is 'i3-msg exit', which behaves exactly like restarting the X session.

**Comment by Askannz** [comment] 2019-06-23 02:17
The latest git version now has auto-logout support for i3, using the command you provided. I've tested it in an i3 session and it works, so I'm closing the issue. Feel free to reopen if needed.

**Closed by Askannz** 2019-06-23 02:17 UTC
Labels: bug
