### ISSUE TITLE
ERROR: the active card is "integrated" but it should be "nvidia". Something went wrong during the last GPU setup... Log at /var/log/optimus-manager/switch/switch-20210907T194329.log

### ISSUE THREAD

**Issue by Schwarzeisc00l** [Askannz/optimus-manager#436] opened 2021-09-07 17:10 UTC
I am using vanilla Arch and i am getting this erorr. The log is down:

[14] INFO: # Xorg pre-start hook
[14] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'nvidia', 'current_mode': None}
[15] INFO: Requested mode is: nvidia
[995] INFO: Available modules: ['nouveau', 'bbswitch', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[996] INFO: Unloading modules ['nouveau'] (if loaded)
[998] INFO: switching=none, nothing to do
[1013] INFO: Loading module nvidia
[1964] INFO: Loading module nvidia_drm
[2711] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
[2712] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20210907T194329', 'requested_mode': 'nvidia'}
[2712] INFO: Xorg pre-start hook completed successfully.
[7] INFO: # Xorg post-start hook
[8] INFO: Running xrandr commands
[11] ERROR: Cannot setup PRIME (xrandr error):
None
[11] INFO: Running /etc/optimus-manager/xsetup-nvidia.sh
[17] INFO: Writing state {'type': 'done', 'switch_id': '20210907T194329', 'current_mode': 'nvidia'}
[18] INFO: Xorg post-start hook completed successfully.

**Comment by nitesh99k** [comment] 2021-10-03 14:52
Same  issue

**Comment by cyrstem** [comment] 2021-10-15 02:42
hi simillar issue 
[19] INFO: # Xorg pre-start hook
[36] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'nvidia', 'current_mode': 'integrated'}
[36] INFO: Requested mode is: nvidia
[629] INFO: Available modules: ['nouveau', 'bbswitch', 'acpi_call', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[630] INFO: Unloading modules ['nouveau'] (if loaded)
[632] INFO: Loading module bbswitch
[634] INFO: Setting GPU power to ON via bbswitch
[6333] INFO: Loading module nvidia
[7943] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 245, in _load_module
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'modprobe nvidia NVreg_UsePageAttributeTable=1' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 51, in main
    setup_kernel_state(config, prev_state, requested_mode)
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 22, in setup_kernel_state
    _nvidia_up(config, hybrid=(requested_mode == "hybrid"))
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 95, in _nvidia_up
    _load_nvidia_modules(config, available_modules)
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 164, in _load_nvidia_modules
    _load_module(available_modules, "nvidia", options=nvidia_options)
  File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 249, in _load_module
    raise KernelSetupError(f"Error running modprobe for {module}: {e.stderr}") from e
optimus_manager.kernel.KernelSetupError: Error running modprobe for nvidia: None
[7946] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[7946] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20211014T213926', 'requested_mode': 'nvidia'}
 andy ideas

**Comment by cyrstem** [comment] 2021-10-15 13:39
@mauricioquintela  hey i think i fixed it by reinstalling python and   reinstalling optimus manager also remove bbswitch from the config file and set it no none  try to figure it out later if this was an issue

**Comment by nwildner** [comment] 2024-07-01 11:44
Sup @mauricioquintela @Schwarzeisc00l @nitesh99k . Is this still reproducing in your setups even with a more modern linux Distro install + `optimus-manager-git`? 

Since this issue isn't active for the last 3 years ago and a lot has changed in many aspects of multiple software, we'll keep this case opened for some days and close it if no answer is provided.

Have a nice week ahead.

**Comment by es20490446e** [comment] 2024-07-15 04:51
Reopen if still there.

**Closed by es20490446e** 2024-07-15 04:51 UTC
