### ISSUE TITLE
Can't switch to Nvidia graphics in Arch

### ISSUE THREAD

**Issue by dwaszuk** [Askannz/optimus-manager#252] opened 2020-05-07 15:13 UTC
Hi, I have a Lenovo Ideapad 720S-14IKB with a NVidia GeForce 940MX. I have Plasma over Arch, and did the following steps:
1. install nvidia package
2. install optimus-manager
3. install optimus-manager-qt
4. install and enable optimus-manager.service
5. reboot my system
After logging in again, no matter which option I choose, it always stays with Intel card (after logout --> login)

Here's the output of:
```
lspci -k | grep -A 2 -E "(VGA|3D)"```
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)
        Subsystem: Lenovo HD Graphics 620
        Kernel driver in use: i915
3c:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 940MX] (rev a2)
        Subsystem: Lenovo GM108M [GeForce 940MX]
        Kernel driver in use: nvidia
```
```
lsmod | egrep "nvidia|nouveau"
nvidia              20504576  0
ipmi_msghandler        73728  2 ipmi_devintf,nvidia
```
```
pacman -Q | grep nvidia
nvidia 440.82-11
nvidia-settings 440.82-1
nvidia-utils 440.82-1
```

But when I run:
```
nvidia-settings

ERROR: Unable to load info from any available system
```

This is the content of the file /etx/X11/xorg.conf.d/10-optimus-manager.conf
```
Section "Device"
        Identifier "intel"
        Driver "modesetting"
        BusID "PCI:0:2:0"
        Option "DRI" "3"
EndSection
```
I've tried reinstalling everything with no better results. Any help will be really appreciated. Thanks in advance

**Comment by Hyper-KVM** [comment] 2020-05-07 18:07
what optimus-manager version is this, can you please provide logs found in /var/log/optimus-manager?

**Comment by dwaszuk** [comment] 2020-05-08 18:42
Hi, thanks for your answer. Sorry I didn't realize I haven't updloaded them.

Here it goes
[boot_setup.log](https://github.com/Askannz/optimus-manager/files/4600950/boot_setup.log)

**Comment by Hyper-KVM** [comment] 2020-05-08 22:21
> Hi, thanks for your answer. Sorry I didn't realize I haven't updloaded them.
> 
> Here it goes
> [boot_setup.log](https://github.com/Askannz/optimus-manager/files/4600950/boot_setup.log)

do you have any other logs? the bootup logs look fine. what about gpu_setup.log?

**Comment by dwaszuk** [comment] 2020-05-08 22:33
That's the only file in the /var/log directory  :( Is there any other place I can look for it?

**Comment by Askannz** [comment] 2020-05-23 08:35
Can you try with the new version (1.3) ?

Once you're logged in run `optimus-manager --status`, and if there is any error, post the attached log file.

**Comment by eatobin** [comment] 2020-06-01 21:21
Hello - I am having the same problem on Manjaro XFCE after an upgrade to 1.3 today. Here is the result of running `optimus-manager --status`:

```
[eric@linux-epth ~]$ optimus-manager --status
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 11, in exec_bash
    out = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', '-c', '__NV_PRIME_RENDER_OFFLOAD=0 glxinfo']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/checks.py", line 117, in _is_gl_provider_nvidia
    out = exec_bash("__NV_PRIME_RENDER_OFFLOAD=0 glxinfo")
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 18, in exec_bash
    raise BashError(
optimus_manager.bash.BashError: Failed to execute '__NV_PRIME_RENDER_OFFLOAD=0 glxinfo' :
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  37
  Current serial number in output stream:  38
name of display: :0.0


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/optimus-manager", line 11, in <module>
    load_entry_point('optimus-manager==1.3', 'console_scripts', 'optimus-manager')()
  File "/usr/lib/python3.8/site-packages/optimus_manager/client/__init__.py", line 24, in main
    fatal = report_errors(state)
  File "/usr/lib/python3.8/site-packages/optimus_manager/client/error_reporting.py", line 52, in report_errors
    active_renderer = get_active_renderer()
  File "/usr/lib/python3.8/site-packages/optimus_manager/checks.py", line 43, in get_active_renderer
    if _is_gl_provider_nvidia():
  File "/usr/lib/python3.8/site-packages/optimus_manager/checks.py", line 119, in _is_gl_provider_nvidia
    raise CheckError("Cannot run glxinfo : %s" % str(e))
optimus_manager.checks.CheckError: Cannot run glxinfo : Failed to execute '__NV_PRIME_RENDER_OFFLOAD=0 glxinfo' :
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  37
  Current serial number in output stream:  38
name of display: :0.0

[eric@linux-epth ~]$
```

Am stuck in Intel.

Thank you for your help.

**Comment by eatobin** [comment] 2020-06-01 21:37
Also here is the output from `systemctl status optimus-manager.service`:

```
● optimus-manager.service - Optimus Manager Commands Daemon
     Loaded: loaded (/usr/lib/systemd/system/optimus-manager.service; enabled; vendor preset: disabled)
     Active: active (running) since Mon 2020-06-01 15:39:38 CDT; 46min ago
    Process: 772 ExecStartPre=/usr/bin/python3 -u -m optimus_manager.hooks.pre_daemon_start (code=exited, status=0/SUCCESS)
    Process: 996 ExecStartPre=/usr/bin/python3 -u -m optimus_manager.hooks.pre_xorg_start (code=exited, status=0/SUCCESS)
   Main PID: 1009 (python3)
      Tasks: 1 (limit: 9452)
     Memory: 23.5M
     CGroup: /system.slice/optimus-manager.service
             └─1009 /usr/bin/python3 -u -m optimus_manager.daemon

Jun 01 15:39:38 linux-epth python3[996]: [907] INFO: Unloading modules ['nvidia_uvm', 'nvidia'] (if loaded)
Jun 01 15:39:38 linux-epth python3[996]: [1019] INFO: Loaded extra Intel Xorg options (0 lines)
Jun 01 15:39:38 linux-epth python3[996]: [1030] INFO: Loaded extra Intel Xorg options (0 lines)
Jun 01 15:39:38 linux-epth python3[996]: [1031] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
Jun 01 15:39:38 linux-epth python3[996]: [1031] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20200601T153937', 'requested_mode': 'intel'}
Jun 01 15:39:38 linux-epth python3[996]: [1059] INFO: Xorg pre-start hook completed successfully.
Jun 01 15:39:38 linux-epth systemd[1]: Started Optimus Manager Commands Daemon.
Jun 01 15:39:38 linux-epth python3[1009]: [3] INFO: # Commands daemon
Jun 01 15:39:38 linux-epth python3[1009]: [3] INFO: Opening UNIX socket
Jun 01 15:39:38 linux-epth python3[1009]: [3] INFO: Awaiting commands
```

Thanks again.

**Comment by Askannz** [comment] 2020-06-08 07:50
Could you switch to the `optimus-manager-git` package and try again ? That client crash is from another bug that was recently fixed (https://github.com/Askannz/optimus-manager/commit/c7a2d051f211df2f5f554f796030516a888aa3e3), and is preventing the error log from showing up.

**Comment by eatobin** [comment] 2020-06-08 12:33
Yes, I will give got a try later today or tonight and report back.

A small complication: I've since installed optimus-switch to see how that
might work and I will have to revert my setup. optimus-switch is stuck in
Nvidia mode. :-) (my usual operating mode)

**Comment by nwildner** [comment] 2024-07-01 10:38
Hello @eatobin and @dwaszuk .

Is this case still relevant to you? Is this behavior still happening with `optimus-manager-git` and a more modern Linux installation?

The last comment on this issue was from 4 years ago so, it may not be reproducing anymore after the fixes that were recently implemented.

I'll close this case in some days if no answer is provided back. Have a nice week.

**Closed** 2024-07-05 08:06 UTC
Labels: bug
