### ISSUE TITLE
nvidia module still loads in intel mode

### ISSUE THREAD

**Issue by m-dwyer** [Askannz/optimus-manager#119] opened 2019-08-27 20:43 UTC
**Describe the bug**
When running an `optimus-manager --set-startup intel` then rebooting, the nvidia kernel module is still loaded despite being blacklisted (see below).

My guess, given I'm running a fairly vanilla arch setup with Xorg+GNOME, is that Xorg is autoloading the module on start (maybe) after the boot process.  I'm not using any custom Xorg.conf.  I've also extracted and checked the contents of my initial ramdisk (/boot/initramfs-linux.img)

If I add `alias <module> off` for the modules listed in /usr/lib/modprobe.d/optimus-manager.conf, this stops the nvidia module loading and resolves the issue. Untested, but `install <module> /bin/false` would likely also work as a more aggressive way of stopping the module loading.

Unrelated, but I also had to set `switching=none` in /etc/optimus-manager/optimus-manager.conf, as nouveau seems to crash my system when loaded on this device.

**System info**
- Arch Linux (5.2.9-arch1-1-ARCH)
- GNOME on XOrg 1.20.5
- GDM
- HP ZBook Studio x360 G5 (Optimus setup -- Intel UHD 630 + Quadro P2000)

**Logs**
```$ optimus-manager --status

Optimus Manager (Client) version 1.1

Current GPU mode : intel
GPU mode requested for next login : intel
GPU mode for next startup : intel

$ lsmod | grep nvidia
nvidia              19103744  18
ipmi_msghandler        69632  2 ipmi_devintf,nvidia 
```
From /var/log/optimus-manager:

[boot_setup.log](https://github.com/Askannz/optimus-manager/files/3548043/boot_setup.log)

**Comment by m-dwyer** [comment] 2019-08-27 20:55
Further comments..

I haven't gone over the code extensively, but my understanding (as someone who doesn't develop Python) is that the optimus-manager.conf blacklist file is permanent (copied in PKGBUILD), so I'm not sure on what the 'best' solution is here.

I previously made my own fedora-prime set of scripts, but this adds/removes the blacklist file.

I'm not sure where/how to determine what is loading the nvidia driver, so disabling aliases seems to be next best bet.  I'm guessing this would need to be done in the daemon seeing as though the blacklist file is permanent?

The nvidia-prime package used on Ubuntu also uses aliases in the blacklist file.  See https://github.com/tseliot/nvidia-prime/blob/cf757cc9585dfc032930379fc81effb3a3d59606/prime-select#L215

**Comment by Askannz** [comment] 2019-08-28 04:20
The nvidia modules are indeed blacklisted by optimus-manager, and dynamically loaded by the daemon when needed. The auto-generated Xorg config should also ensure that the display server isn't picking up the Nvidia GPU (unless GNOME is doing something I'm not aware of).

Could you try with the [latest stable version](https://aur.archlinux.org/packages/optimus-manager/) instead of the git version ?

Alternatively, try with power management disabled with this config :

```
[optimus]
switching=none
pci_power_control=no
```

This will obviously decrease battery life, but should at least help pinpointing the issue.

**Comment by m-dwyer** [comment] 2019-08-28 11:24
I went back to the stable version in AUR which didn't make a difference.  I also set `switching=none` and `pci_power_control=no` -- same issue in that the nvidia module still loads.

[boot_setup.log](https://github.com/Askannz/optimus-manager/files/3550583/boot_setup.log)

**Comment by Askannz** [comment] 2020-03-05 10:33
Currently going through my backlog of issues and coming back to this one.

I'm still unsure what's going on here. Something we haven't checked, is the nvidia driver auto-loaded if you disable the login manager and boot straight to a TTY ? (assuming the issue is still there, of course). Just to confirm your hypothesis that it's Xorg loading up the module. But honestly that would be weird since I cannot reproduce the issue (even when I let the Nvidia card stay powered on an available throughout startup).

It'd be great if you could try with a different login manager as well.

**Comment by benjamimgois** [comment] 2021-03-23 12:40
I was having this same issue on my system. What solves the issue for me was setting to option to disconect the GPU. Hope it helps.

![image](https://user-images.githubusercontent.com/7688496/112147405-71d71b80-8bbb-11eb-964c-389858fc86b0.png)


██████████████████  ████████   benjamim@manjaro 
██████████████████  ████████   ---------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: VivoBook_ASUSLaptop X512JP_X512JP 1.0 
████████            ████████                Kernel: 5.11.6-1-MANJARO 
████████  ████████  ████████   Uptime: 3 mins 
████████  ████████  ████████   Packages: 1339 (pacman), 10 (flatpak) 
████████  ████████  ████████   Shell: zsh 5.8 
████████  ████████  ████████   Resolution: 1920x1080 
████████  ████████  ████████   DE: GNOME 3.38.4 
████████  ████████  ████████   WM: Mutter 
████████  ████████  ████████   WM Theme: Matcha-dark-sea 
████████  ████████  ████████   Theme: Matcha-sea [GTK2/3] 
████████  ████████  ████████   Icons: Papirus-Dark-Maia [GTK2/3] 
                               Terminal: gnome-terminal 
                               CPU: Intel i7-1065G7 (8) @ 3.900GHz 
                               GPU: Intel Iris Plus Graphics G7 
                               Memory: 2237MiB / 15817MiB

**Comment by nwildner** [comment] 2024-07-01 10:42
Hello @m-dwyer . Is this issue still reproducing? Were you able to give it a try enabling the option provided by the previous comment here to auto disconnect ?

Since the last update on this case was from 3 years ago, we'll keep this case opened for some days and close it if no answer is provided.

Have a nice week ahead.

**Closed** 2024-07-03 08:42 UTC
Labels: bug
