### ISSUE TITLE
Cant switch to Nvidia mode or Hybrid mode

### ISSUE THREAD

**Issue by coolbirdd** [Askannz/optimus-manager#425] opened 2021-07-25 06:02 UTC
**Describe the bug**
I cannot switch from integrated mode, with a terminal command nor from the optimus-manager-qt

**System info**
Please include :
- Manjaro 5.10
- KDE
- SDDM
- Acer Nitro AN515-51
- stable release optimus-manager

**optimusmanager.conf**
DRI=0
driver=modesetting
tearfree=

[intel]
DRI=0
accel=
driver=modesetting
modeset=yes
tearfree=

[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
dynamic_power_management=no
ignore_abi=no
modeset=yes
options=overclocking

[optimus]
auto_logout=yes
pci_power_control=no
pci_remove=no
pci_reset=no
startup_auto_battery_mode=integrated
startup_auto_extpower_mode=nvidia
startup_mode=integrated
switching=none

**Logs**
ERROR: a GPU setup was initiated but Xorg post-start hook did not run.
Log at /var/log/optimus-manager/switch/switch-20210723T205022.log
If your login manager is GDM, make sure to follow those instructions:
https://github.com/Askannz/optimus-manager#important--gnome-and-gdm-users
If your display manager is neither GDM, SDDM nor LightDM, or if you don't use one, read the wiki:
https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting
Config parsing : error in option "dri" in section [intel] : invalid value "0"
Config parsing : error in option "dri" in section [amd] : invalid value "0"
Cannot execute command because of previous errors.

[33] INFO: # Xorg pre-start hook
[33] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'integrated', 'current_mode': None}
[33] INFO: Requested mode is: integrated
[563] INFO: Available modules: ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[564] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[567] INFO: switching=none, nothing to do
[585] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
[585] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20210721T163322', 'requested_mode': 'integrated'}
[585] INFO: Xorg pre-start hook completed successfully.

**Comment by T4rtP1ck13** [comment] 2021-09-05 23:13
What display manager are you using?

**Comment by nwildner** [comment] 2024-07-01 12:06
@T4rtP1ck13 , it's on the initial report: SDDM
@coolbirdd  are you still interested on this case? Are you able to reproduce it using `optimus-manager-git` and a more recent Linux install?

Since this issue isn't active for the last 3 years ago and a lot has changed in many aspects of multiple software, we'll keep this case opened for some days and close it if no further comments are provided.

Have a nice week ahead.

**Closed** 2024-07-05 11:51 UTC
