### ISSUE TITLE
Optimus Manager in Hybrid mode has slow performance, when using external monitors

### ISSUE THREAD

**Issue by MrInfusion** [Askannz/optimus-manager#333] opened 2020-10-20 13:47 UTC
When in hybrid mode, external monitors aren't smooth, and only locked down to maybe 30hz or something. And if I also close the lid of the notebook, it isn't even usable anymore with a total framerate of 5 to 10fps. But when using NVIDIA Mode everything works fine again. 

I am using two Dell monitors with a resolution of 1440p (2560x1440) and a refresh rate of 60hz. optimus-manager works fine and doesn't give any errors, it's just a poor performance when in hybrid mode with these two monitors. Otherwise hybrid mode works fine as usual. 

Notebook: XMG Fusion 15
1. GPU: Nvidia Geforce RTX 2070 Max Q Design
2. GPU: Intel UHD Graphics 630
CPU: Intel Core i7-9750H
1TB M.2 SSD Crucial
16 RAM

**Comment by kayg04** [comment] 2020-10-20 14:17
Facing the same issue. Also would like to add that I notice terrible tearing on both external monitors when in hybrid mode.

**Comment by MrInfusion** [comment] 2020-10-21 08:57
> Facing the same issue. Also would like to add that I notice terrible tearing on both external monitors when in hybrid mode.

I also have this issue when in NVIDIA Mode. Try Forcing "Full Composition Pipeline" in Nvidia Settings.

**Comment by kayg04** [comment] 2020-10-21 09:25
Though I do get that option in Nvidia mode, there is no such option when in hybrid mode. That's because both outputs are being rendered by the Intel GPU.

21-Oct-2020 14:32:38 MrInfusion <notifications@github.com>:

**Comment by Askannz** [comment] 2020-10-31 01:41
Very likely a duplicate of https://github.com/Askannz/optimus-manager/issues/314.

**Closed by Askannz** 2020-10-31 01:41 UTC
