### ISSUE TITLE
Switching Failed Due to Kernel Setup Error?

### ISSUE THREAD

**Issue by YottaGitHub** [Askannz/optimus-manager#495] opened 2022-05-15 00:17 UTC
Hi there. For some reason, I am unable to switch to nvidia mode. Upon running `optimus-manager --switch nvidia`, and re-logging in, I run `optimus-manager --status` and get the following error message:

`ERROR: the latest GPU setup attempt failed at Xorg pre-start hook.
Log at /var/log/optimus-manager/switch/switch-20220514T171040.log
Cannot execute command because of previous errors.`

I'm fairly new to Linux, but I know my way around, and I've tried every troubleshooting step I could find to alleviate this issue to no avail. I'm not sure what to do. Please help. Thank you in advance.

Here is the error log:
> [7] INFO: # Xorg pre-start hook
> [7] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'nvidia', 'current_mode': 'integrated'}
> [7] INFO: Requested mode is: nvidia
> [497] INFO: Available modules: ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
> [497] INFO: Unloading modules ['nouveau'] (if loaded)
> [499] INFO: switching=none, nothing to do
> [1799] INFO: Resetting Nvidia PCI device
> [1799] INFO: Starting hot reset sequence
> [1818] INFO: Removing Nvidia from PCI bridge
> [1832] INFO: Writing "1" to /sys/bus/pci/devices/0000:01:00.0/remove
> [1835] INFO: Writing "1" to /sys/bus/pci/devices/0000:01:00.1/remove
> [2071] INFO: Triggering PCI hot reset of bridge 00:01.0
> [2323] INFO: Rescanning PCI bus
> [2443] INFO: Setting Nvidia PCI power state to on
> [2457] INFO: Writing "on" to /sys/bus/pci/devices/0000:01:00.0/power/control
> [2457] INFO: Writing "on" to /sys/bus/pci/devices/0000:01:00.1/power/control
> [2473] INFO: Loading module nvidia
> [2487] INFO: Loading module nvidia_drm
> [2570] ERROR: Xorg pre-start setup error
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 245, in _load_module
>     subprocess.check_call(
>   File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command 'modprobe nvidia_drm modeset=1' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 51, in main
>     setup_kernel_state(config, prev_state, requested_mode)
>   File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 22, in setup_kernel_state
>     _nvidia_up(config, hybrid=(requested_mode == "hybrid"))
>   File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 95, in _nvidia_up
>     _load_nvidia_modules(config, available_modules)
>   File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 175, in _load_nvidia_modules
>     _load_module(available_modules, "nvidia_drm", options=nvidia_drm_options)
>   File "/usr/lib/python3.10/site-packages/optimus_manager/kernel.py", line 249, in _load_module
>     raise KernelSetupError(f"Error running modprobe for {module}: {e.stderr}") from e
> optimus_manager.kernel.KernelSetupError: Error running modprobe for nvidia_drm: None
> [2571] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
> [2571] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20220514T171040', 'requested_mode': 'nvidia'}

**Comment by nwildner** [comment] 2024-07-01 13:21
Looks like there was an error when modprobing `nvidia_drm` module here.

@YottaGitHub were you able to reproduce this with a more recent build of optimus-manager, specially `optimus-manager-git` and a more updated system?

Since this issue isn't active for the last 2 years ago and a lot has changed in many aspects of multiple software, we'll keep this case opened for some days and close it if no further comments are provided. We're dealing with backlog here to try to keep `optimus-manager` in a good shape and active as a project.

Have a nice week ahead.

**Closed** 2024-07-05 11:53 UTC
