### ISSUE TITLE
Nvidia mode significantly slower than other modes

### ISSUE THREAD

**Issue by gl00ten** [Askannz/optimus-manager#557] opened 2024-01-16 04:58 UTC
**Describe the bug**
When switching to nvidia the framerate drops a lot when compared to hybrid or integrated.

I tested using this: **glmark2**

**System info**
Please include :OS: Manjaro Linux x86_64 
Host: ASUS TUF Gaming A15 FA506II_FA506II 1.0 
Kernel: 6.7.0-0-MANJARO 
Uptime: 13 mins 
Packages: 1319 (pacman) 
Shell: bash 5.2.21 
Resolution: 1920x1080 
DE: Plasma 5.27.10 
WM: KWin 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze [GTK2/3] 
Terminal: konsole 
CPU: AMD Ryzen 7 4800H with Radeon Graphics (16) @ 2.900GHz 
GPU: NVIDIA GeForce GTX 1650 Ti Mobile 
GPU: AMD ATI Radeon RX Vega 6 
Memory: 3655MiB / 31513MiB

**optimus-manager --status**                                                                                                                                                     ✔ 
Optimus Manager (Client) version 1.5

Current GPU mode : hybrid
GPU mode requested for next login : no change
GPU at startup : hybrid
Temporary config path: no

**/etc/optimus-manager/optimus-manager.conf**
#i tried a bunch of stuff. initially i was focused on decreasing power consumption but then i wanted to benchmark
[optimus]
startup_mode=hybrid

#startup_mode=integrated
#switching=nouveau
#pci_power_control=yes
#pci_remove=no
#pci_reset=no

#[nvidia]
#dynamic_power_management=fine

**benchmarking results**
hybrid
[build] use-vbo=false: FPS: 9311 FrameTime: 0.107 ms
[build] use-vbo=true: FPS: 10802 FrameTime: 0.093 ms
[texture] texture-filter=nearest: FPS: 8747 FrameTime: 0.114 ms

integrated
[build] use-vbo=false: FPS: 9463 FrameTime: 0.106 ms
[build] use-vbo=true: FPS: 10475 FrameTime: 0.095 ms
[texture] texture-filter=nearest: FPS: 8965 FrameTime: 0.112 ms

nvidia
[build] use-vbo=false: FPS: 2164 FrameTime: 0.462 ms
[build] use-vbo=true: FPS: 2667 FrameTime: 0.375 ms
[texture] texture-filter=nearest: FPS: 6234 FrameTime: 0.160 ms

**i can hear the fan spin way faster and see the wattage rising in _powertop_  but in the end i get less frames. any idea why?**

**note:**
i did change the /etc/sddm.conf file
[X11]
#DisplayCommand=/usr/share/sddm/scripts/Xsetup
#DisplayStopCommand=/usr/share/sddm/scripts/Xstop

**Comment by nwildner** [comment] 2024-07-01 13:02
Closing as a duplicate of #498
It also might not be entirely related to `optimus-manager` but, please follow that other issue and post any findings there
Have a nice week.

**Closed by nwildner** 2024-07-01 13:02 UTC
