### ISSUE TITLE
Optimus-manager able to switch, but unable to get current state

### ISSUE THREAD

**Issue by mauricioquintela** [Askannz/optimus-manager#451] opened 2021-12-04 22:12 UTC
**Describe the bug**

A recent kernel update caused a "few" issues with optimus-manager related with [power management](https://github.com/Askannz/optimus-manager/issues/444). This lead me to reconfigure everything.
Optimus-manager itself is now "working" again (i.e., switching works fine), but any attempt to interact with optimus-manager leads to it complaining that  

```
ERROR: a GPU setup was initiated but Xorg post-start hook did not run.
Log at /var/log/optimus-manager/switch/switch-20211204T215253.log
If your login manager is GDM, make sure to follow those instructions:
https://github.com/Askannz/optimus-manager#important--gnome-and-gdm-users
If your display manager is neither GDM, SDDM nor LightDM, or if you don't use one, read the wiki:
https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting
Cannot execute command because of previous errors
```

Log does not provide any useful information, reading 
```
[32] INFO: # Xorg pre-start hook
[32] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'integrated', 'current_mode': None}
[32] INFO: Requested mode is: integrated
[1352] INFO: Available modules: ['nouveau', 'bbswitch', 'acpi_call', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[1352] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[1359] INFO: switching=nouveau, nothing to do
[1359] INFO: Loading module nouveau
[2845] INFO: Setting Nvidia PCI power state to auto
[2905] INFO: Writing "auto" to /sys/bus/pci/devices/0000:01:00.0/power/control
[2932] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
[2932] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20211204T215253', 'requested_mode': 'integrated'}
[2932] INFO: Xorg pre-start hook completed successfully.
```

**System info**
Please include :
- Manjaro (kernel 5.15.6)
- i3
- LightDM
- The version of optimus-manager you are using : latest stable release 1.4
- Your custom optimus-manager configuration file at `/etc/optimus-manager/optimus-manager.conf`, if you made one

**Logs**
Run `optimus-manager --status` in a console, and if an error message appears, post it here. 
```
ERROR: a GPU setup was initiated but Xorg post-start hook did not run.
Log at /var/log/optimus-manager/switch/switch-20211204T215253.log
If your login manager is GDM, make sure to follow those instructions:
https://github.com/Askannz/optimus-manager#important--gnome-and-gdm-users
If your display manager is neither GDM, SDDM nor LightDM, or if you don't use one, read the wiki:
https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting
Cannot execute command because of previous errors.
```
The message should also point you to a log path, attach it here as well. 
[switch-20211204T215253.log](https://github.com/Askannz/optimus-manager/files/7654789/switch-20211204T215253.log)
```
[32] INFO: # Xorg pre-start hook
[32] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'integrated', 'current_mode': None}
[32] INFO: Requested mode is: integrated
[1352] INFO: Available modules: ['nouveau', 'bbswitch', 'acpi_call', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[1352] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[1359] INFO: switching=nouveau, nothing to do
[1359] INFO: Loading module nouveau
[2845] INFO: Setting Nvidia PCI power state to auto
[2905] INFO: Writing "auto" to /sys/bus/pci/devices/0000:01:00.0/power/control
[2932] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
[2932] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20211204T215253', 'requested_mode': 'integrated'}
[2932] INFO: Xorg pre-start hook completed successfully.
```
If there is no error message but you are still experiencing issues, grab the most recent files in `/var/log/optimus-manager/switch/` and `/var/log/optimus-manager/daemon/`.
[daemon-20211204T215253.log](https://github.com/Askannz/optimus-manager/files/7654787/daemon-20211204T215253.log)
```
[97] INFO: # Daemon pre-start hook
[98] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[102] INFO: Copying /etc/optimus-manager/optimus-manager.conf to /var/lib/optimus-manager/tmp/config_copy.conf
[111] INFO: Startup mode is: integrated
[112] INFO: Writing state {'type': 'pending_pre_xorg_start', 'requested_mode': 'integrated', 'current_mode': None}
[112] INFO: Daemon pre-start hook completed successfully.
[112] INFO: Calling Xorg pre-start hook.
[2] INFO: # Commands daemon
[2] INFO: Opening UNIX socket
[2] INFO: Awaiting commands
```

**Comment by cyrstem** [comment] 2021-12-27 20:59
im getting this same error any fix yet or whats going on ?
@mauricioquintela

**Comment by mauricioquintela** [comment] 2022-01-01 16:32
I was not able to get it to work, so I just kinda gave up and switched to [nvidia-xrun](https://github.com/michelesr/nvidia-xrun) @cyrstem

**Comment by nwildner** [comment] 2024-07-01 16:12
Closing this since the original reporter migrated to `nvidia-xrun` so, he/she/they might not be able to reproduce this again.

Also, this is a long aging case and people should track `optimus-manager-git` now where a lot of recent PR's got merged.

**Closed by nwildner** 2024-07-01 16:12 UTC
Labels: bug
