### ISSUE TITLE
Can't switch to Nvidia mode

### ISSUE THREAD

**Issue by xavierfnk** [Askannz/optimus-manager#234] opened 2020-03-29 18:33 UTC
Hi, since the latest Manjaro update on my Dell XPS 9570, I can't switch to Nvidia mode. Uninstalling and reinstalling did not work. What's weird is, looking at the gpu_setup logs, optimus-manager tries to find a `nvidia_enable.sh` file that doesn't exist.

**System info**

OS: `Manjaro 19.0.2 Kyria`
Kernel: `x86_64 Linux 5.4.27-1-MANJARO`
DE: KDE 5.68.0 / Plasma 5.18.3
WM: KWin
CPU: Intel Core i7-8750H
GPU: Intel Corporation UHD Graphics 630 & Nvidia GeForce GTX 1050 Ti

**Logs**

Here is what happens in `gpu_setup.log` :

```
2020-03-29 07:38:10 PM +0200 ==================== 

Optimus Manager (Setup script) version 1.2.2
Setting up the GPU
Checking status of optimus-manager.service
Cleaning up leftover Xorg conf
Loading config
Requested mode : nvidia
Checking for GDM display servers
Available kernel modules : ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset']
Setting up base state
Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia'] (if loaded)
Unloading modules ['nouveau'] (if loaded)
Running /etc/optimus-manager/nvidia-enable.sh
ERROR : cannot run /etc/optimus-manager/nvidia-enable.sh. Continuing anyways. Error is : Failed to execute '/etc/optimus-manager/nvidia-enable.sh' : bash: /etc/optimus-manager/nvidia-enable.sh: No such file or directory
Setting up Nvidia state
Loading module nvidia
Cannot setup GPU : kernel setup error : error running modprobe for nvidia : Failed to execute 'modprobe nvidia NVreg_UsePageAttributeTable=1' : modprobe: ERROR: could not insert 'nvidia': No such device
```

**Comment by Ridzu95** [comment] 2020-03-29 18:51
My bad for not figuring out `nvidia_enable.sh` was just here if I had custom configuration to add.

For the `Cannot setup GPU : kernel setup error : error running modprobe for nvidia : Failed to execute 'modprobe nvidia NVreg_UsePageAttributeTable=1' : modprobe: ERROR: could not insert 'nvidia': No such device` error, I solved the problem by setting `pci_power_control` and `pci_remove` vars to `no` in `optimus-manager.conf`. I don't know if it's ideal but it works.

**Comment by elithrade** [comment] 2020-03-30 14:42
I am having the similar issue after I upgraded my kernel to 5.5. I am running Manjaro. When I switch to `nvidia` it always fallback to `intel`.

**Comment by elithrade** [comment] 2020-03-31 06:29
In my case, I can confirm that, after the latest Manjaro upgrade, I can switch between `intel` and `nvidia` now. It is not an issue with `optimus-manager` in my case.

**Comment by aronszabo** [comment] 2020-05-04 22:41
Hi all,
I have the same problem, switching to nvidia stopped working some days ago. My laptop is exactly the same model.
Setting the options in `optimus-manager.conf` works, but gives the warning message about battery life.
My `gpu_setup.log`:
```
Optimus Manager (Setup script) version 1.2.2
Setting up the GPU
Checking status of optimus-manager.service
Cleaning up leftover Xorg conf
Removed /etc/X11/xorg.conf.d/10-optimus-manager.conf
Loading config
Requested mode : nvidia
Checking for GDM display servers
Available kernel modules : ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset']
Setting up base state
Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia'] (if loaded)
Unloading modules ['nouveau'] (if loaded)
Running /etc/optimus-manager/nvidia-enable.sh
ERROR : cannot run /etc/optimus-manager/nvidia-enable.sh. Continuing anyways. Error is : Failed to execute '/etc/optimus-manager/nvidia-enable.sh' : bash: /etc/optimus-manager/nvidia-enable.sh: No such file or directory
Nvidia card not visible in PCI bus, rescanning
ERROR : Nvidia card not showing up in PCI bus after rescan. Continuing anyways.
ERROR : cannot set PCI power management state. Continuing. Error is : Nvidia not in PCI bus
Setting up Nvidia state
Loading module nvidia
Cannot setup GPU : kernel setup error : error running modprobe for nvidia : Failed to execute 'modprobe nvidia NVreg_UsePageAttributeTable=1' : modprobe: ERROR: could not insert 'nvidia': No such device
```

**Comment by aronszabo** [comment] 2020-05-30 15:41
Still the same problem, but just discovered, that Auto mode works without problem (sets Nvidia card when on AC power)

**Comment by Askannz** [comment] 2020-06-07 02:02
@aronszabo `startup_mode=auto` works but `startup_mode=nvidia` doesn't ? That's weird, to say the least. Assuming you're using the latest release (v1.3) or the -git version, can you run `optimus-manager --status` after a failed startup and send the atached log ?

I would also recommend disabling any power management tweak from the config file (remove `switching` and any `pci_*` parameter).

**Comment by cuppajoeman** [comment] 2020-06-14 15:27
Hey, I'm also having this problem, 

Computer: Lenovo Thinkpad T420

Hardware: 
- Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
- NVIDIA Corporation GF119M [Quadro NVS 4200M] (rev a1)

OS: Arch linux with lightdm & i3

Using this nvidia package from the AUR: https://aur.archlinux.org/packages/nvidia-390xx-dkms/

when I run `optimus-manager --switch nvidia`, after logging in it fails, and my my log looks like this 

```
[14] INFO: # Xorg pre-start hook
[14] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'nvidia', 'current_mode': 'intel'}
[14] INFO: Requested mode is: nvidia
[14] INFO: Checking for GDM display servers
[996] INFO: Available modules: ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[996] INFO: Unloading modules ['nouveau'] (if loaded)
[1029] INFO: Loading module nvidia
[1993] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 11, in exec_bash
    out = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', '-c', 'modprobe nvidia NVreg_UsePageAttributeTable=1']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 179, in _load_module
    exec_bash("modprobe %s %s" % (module, options))
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 18, in exec_bash
    raise BashError(
optimus_manager.bash.BashError: Failed to execute 'modprobe nvidia NVreg_UsePageAttributeTable=1' :
modprobe: ERROR: could not insert 'nvidia': No such device


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 45, in main
    setup_kernel_state(config, prev_state, requested_mode)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 21, in setup_kernel_state
    _nvidia_up(config)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 56, in _nvidia_up
    _load_nvidia_modules(config, available_modules)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 109, in _load_nvidia_modules
    _load_module(available_modules, "nvidia", options="NVreg_UsePageAttributeTable=%d" % pat_value)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 181, in _load_module
    raise KernelSetupError("error running modprobe for %s : %s" % (module, str(e)))
optimus_manager.kernel.KernelSetupError: error running modprobe for nvidia : Failed to execute 'modprobe nvidia NVreg_UsePageAttributeTable=1' :
modprobe: ERROR: could not insert 'nvidia': No such device

[1998] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
d1998] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20200614T121918', 'requested_mode': 'nvidia'}
```

**Comment by Askannz** [comment] 2020-06-15 11:09
@cuppajoeman from Intel mode , does `sudo modprobe nvidia` return the same error ? And can you see your Nvidia card in `lspci` ?

**Comment by cuppajoeman** [comment] 2020-06-15 17:02
@Askannz  Yes, running `sudo modprobe nvidia` returns `modprobe: ERROR: could not insert 'nvidia': No such device`.

Also I can see my card in `lspci`
```
cuppajoeman@cup:~$ lspci  | grep -e 'VGA'
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
01:00.0 VGA compatible controller: NVIDIA Corporation GF119M [Quadro NVS 4200M] (rev a1)
```

**Comment by cuppajoeman** [comment] 2020-06-16 13:28
I managed to get it working, I installed the previously mentioned package through yay (an aur helper) and that didn't seem to work, so I manually got the packages from the aur for nvidia-390xx, after that everything went smoothly and no more errors!

**Comment by mitran** [comment] 2020-08-27 13:09
Also had the `No such device` problem since 1.3 and used optimus-manager-git 1.2.2.
Up until today I found this talks article: https://wiki.archlinux.org/index.php/Talk:Dell_XPS_15_9570
My device is Dell 7577 with 1060 Max-q. Using following settings everything worked like a charm: battery consumption in `intel` mode, return from hibernation in `nvidia` mode.

/etc/optimus-manager/optimus-manager.conf
```
[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=

[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
ignore_abi=no
modeset=yes
options=overclocking

[optimus]
auto_logout=yes
pci_power_control=yes
pci_remove=yes
pci_reset=no
startup_auto_battery_mode=intel
startup_auto_extpower_mode=nvidia
startup_mode=auto
switching=custom
```

/etc/optimus-manager/nvidia-enable.sh
```
# change PCIe power control
echo -n on > /sys/bus/pci/devices/0000\:00\:01.0/power/control
sleep 0.5 
# rescan for NVIDIA card (defaults to power/control = on)
echo -n 1 > /sys/bus/pci/rescan
# someone said that modprobe nvidia is needed also to load nvidia, to check
modprobe nvidia
```

/etc/optimus-manager/nvidia-disable.sh
```
modprobe -r nvidia_drm
modprobe -r nvidia_uvm
modprobe -r nvidia_modeset
modprobe -r nvidia

# Change NVIDIA card power control
echo -n auto > /sys/bus/pci/devices/0000\:01\:00.0/power/control
sleep 0.5 
echo -n auto > /sys/bus/pci/devices/0000\:00\:01.0/power/control
```

On 1.2.2 everything worked with `acpi_call`.

**Comment by nwildner** [comment] 2024-07-02 11:13
Hello @mitran .

Can you confirm if this issue is still happening using `optimus-manager-git` and a more recent Kernel and Nvidia versions?

Since this issue isn't active for the last 4 years ago and a lot has changed in many aspects of multiple software, we'll keep this case opened for some days and close it if no further comments are provided. We're dealing with backlog here to try to keep `optimus-manager` in a good shape and active as a project.

Have a nice week ahead.

**Closed** 2024-07-03 08:45 UTC
