### ISSUE TITLE
Failed to Switch, Won't Switch on Reboot, and Optimus Manager Qt Displaying Wrong Mode

### ISSUE THREAD

**Issue by domglusk** [Askannz/optimus-manager#535] opened 2023-03-21 21:32 UTC
I'm trying to switch to nvidia mode to use gpu-screen-recorder but it just simply isnt working.
Info (everything is the newest version available):
EndeavourOS
KDE Plasma
Nvidia-dkms
Zen Kernel
[switch-20230321T162610.log](https://github.com/Askannz/optimus-manager/files/11033888/switch-20230321T162610.log)
[switch-20230321T162357.log](https://github.com/Askannz/optimus-manager/files/11033889/switch
[optimus-manager.conf.txt](https://github.com/Askannz/optimus-manager/files/11033897/optimus-manager.conf.txt)
-20230321T162357.log)
[daemon-20230321T162610.log](https://github.com/Askannz/optimus-manager/files/11033893/daemon-20230321T162610.log)
[10-optimus-manager.conf.txt](https://github.com/Askannz/optimus-manager/files/11033912/10-optimus-manager.conf.txt)

Hybrid Mode works just fine, its just using nvidia mode that won't work. And I don't have an xorg.conf, optimus manager is supposed to make one I believe.

**Comment by nwildner** [comment] 2024-07-01 14:58
Sup @domglusk . Is this issue still reproducing to you? Could you please try `optimus-manager-git` ?

Also, can we have more details on the KDE version, nvidia version, kernel version number, laptop version and GPU you are using?

Since this issue isn't active for the last year and a lot has changed in many aspects of multiple software, we'll keep this case opened for some days and close it if no further comments are provided. We're dealing with backlog here to try to keep `optimus-manager` in a good shape and active as a project.

Have a nice week ahead.

**Comment by domglusk** [comment] 2024-07-02 21:03
I've switched from using EndeavourOS to OpenSUSE Tumbleweed, sorry I don't have anyway to test.

**Comment by nwildner** [comment] 2024-07-02 21:05
Got it. Thanks for the feedback anyways.
Closing this for backlog purposes.

**Closed by nwildner** 2024-07-02 21:05 UTC
