### ISSUE TITLE
could not connect to i3 on socket /tmp/i3-ipc.sock

### ISSUE THREAD

**Issue by SHx7ejs7fCrP** [Askannz/optimus-manager#461] opened 2022-01-06 18:57 UTC
this occurs on endeavouros

[work@work ~]$ sudo optimus-manager --switch nvidia
[sudo] password for work: 
WARNING : no power management option is currently enabled (this is the default since v1.2). Switching between GPUs will work but you will likely experience poor battery life.
Follow instructions at https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options to enable power management.

You are about to switch GPUs. This will forcibly close all graphical sessions and all your applications WILL CLOSE.
(you can pass the --no-confirm option to disable this warning)
Continue ? (y/N)
> y
Switching to mode : nvidia
i3-msg: Could not connect to i3 on socket /tmp/i3-ipc.sock: No such file or directory
Obt-Message: Failed to open an Input Method
/bin/sh: line 1: awesome-client: command not found
/bin/sh: line 1: bspc: command not found
/bin/sh: line 1: qtile-cmd: command not found
[work@work ~]$ 
[work@work ~]$ sudo optimus-manager --switch intel
A GPU switch from integrated to nvidia is pending.
Log out and log back in to apply.
Warning: mode "intel" is deprecated, use "integrated" instead
WARNING : no power management option is currently enabled (this is the default since v1.2). Switching between GPUs will work but you will likely experience poor battery life.
Follow instructions at https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options to enable power management.

You are about to switch GPUs. This will forcibly close all graphical sessions and all your applications WILL CLOSE.
(you can pass the --no-confirm option to disable this warning)
Continue ? (y/N)
> Y
Switching to mode : integrated
i3-msg: Could not connect to i3 on socket /tmp/i3-ipc.sock: No such file or directory
Obt-Message: Failed to open an Input Method
/bin/sh: line 1: awesome-client: command not found
/bin/sh: line 1: bspc: command not found
/bin/sh: line 1: qtile-cmd: command not found

**Comment by Allorth** [comment] 2023-04-05 05:31
I'm trying to get optimus-manager to work on arch (really arco-linux) using qtile and I get the same error and no effect running either  `prime-offload && optimus-manager --switch nvidia` or `prime-offload && optimus-manager --switch integrated`. Is there any update on this bug?

**Comment by nwildner** [comment] 2024-07-18 15:13
@Allorth , please try the `optimus-manager-git` package

@SHx7ejs7fCrP , can you confirm that this issue isn't at endeavourOS side and the i3-wm socket file is not located in other place by default like inside `/run` ?

```
i3-msg: Could not connect to i3 on socket /tmp/i3-ipc.sock: No such file or directory
```

This message indicates that this socket is somewhere else on the system.

Also, please let us know if you are still interested on this issue after updating your optimus manager to the last version available at `optimus-manager-git` package.

**Comment by nwildner** [comment] 2024-08-02 09:12
Closing by timeout.

Feel free to reopen it if you think this case needs extra attention and this issue is still reproducing and you have made sure this i3 socket behavior isn't something specific and "by design" of endeavourOS.

**Closed by nwildner** 2024-08-02 09:12 UTC
Labels: bug
