### ISSUE TITLE
Nvidia GPU power state not preserved after hibernation

### ISSUE THREAD

**Issue by oyhel** [Askannz/optimus-manager#191] opened 2019-12-26 12:03 UTC
Optius-manager works great for suspending the nvidia card. However, after waking from suspend the nvidia card is activated again and I have to switch back to nvidia and then to intel only to have the card suspend again. I have tried the various solutions for power management described in the wiki, but none seems to address this problem. Any help to fix this would be greatly appreciated!

**System info**
Please include :
- Your distribution
Manjaro KDE, kernel 5.4 (tested 4.19 and 5.2 as well). Tested with Nvidia 330,335,340 drivers
- Your desktop manager (KDE, GNOME, Cinnamon...), if you have one
KDE 5.17
- You display manager (SDDM, GDM, LightDM...), if you have one. If you do not know, you are probably using the one coming with your desktop manager.
SDDM
- Your laptop model, if you think it could be related to the problem
Thinkpad X1 Extreme gen1
- The version of optimus-manager you are using : latest stable release (optimus-manager), or the latest Git version (optimus-manager-git)
1.2.2 
**Logs**
https://pastebin.com/RUsHnbFB

**Comment by Askannz** [comment] 2020-01-10 23:13
Suspend is all kinds of broken on Nvidia, that's not news. Sadly there's not much I can do about it. I'll see if I can reproduce that issue on my machine, but it might be specific to your laptop model.

**Comment by openmindead** [comment] 2020-01-14 09:43
I had the same issue until I set switching method to "bbswitch" and pcireset to "no".

**Comment by Askannz** [comment] 2020-10-10 08:47
So, turns out a pretty simple fix for this issue is to have optimus-manager add a hook to systemd that powers the card on before sleep and powers it back off after resume. Tested on my machine (using bbswitch), and it seems to work. Let me know if it works for you too ! It should be in the latest master branch.

**Comment by nwildner** [comment] 2024-06-20 16:39
Hello @oyhel .

Did you have the time to fix this issue? Is this still relevant to you?
#270 and #317 implemented the changes needed to deal with the power during sleep/resume.

Cheers.

**Comment by oyhel** [comment] 2024-06-20 16:47
Thank you for coming back to me. I am not using dedicated graphics on my laptop these days so I am not sure whether it has been resolved or not, but the issue is not that relevant for me these days.

**Closed** 2024-06-30 06:24 UTC
Labels: bug, hardware
