### ISSUE TITLE
KernelSetupError in Manjaro

### ISSUE THREAD

**Issue by Aya-Komichi** [Askannz/optimus-manager#363] opened 2021-01-16 10:29 UTC
I am unsure if this was a problem on my end or a problem with the package itself, odds are it might be the first case, but I figured I could get some help figuring the problem here. In case this isn't the right place to get help, please point me where I should try next.

Before I attempted to install optimus-manager, I renamed the files `/etc/X11/mhwd.d/nvidia.conf` and `/etc/X11/xorg.conf.d/90-mhwd.conf`. I don't know if I missed any other files I should have renamed, if I did please tell me which other files I should try and rename before attempting to install this again. Both files mentioned only had comments, nothing else. After that I also did go to /etc/sddm.conf and commented `#DisplayCommand` and `DisplayStopCommand` like it was said on the README of this repository.

After I installed the package and rebooted, I went to check the process running, I saw that while it was active and running there was an error thrown:

`
Jan 15 20:24:24 ManjaroOmen python3[612]:   File "/usr/lib/python3.9/site-packages/optimus_manager/kernel.py", line 198, in _unload_modules
Jan 15 20:24:24 ManjaroOmen python3[612]:     raise KernelSetupError("Cannot unload modules %s : %s" % (str(modules_to_unload), str(e)))
Jan 15 20:24:24 ManjaroOmen python3[612]: optimus_manager.kernel.KernelSetupError: Cannot unload modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] : Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' :
Jan 15 20:24:24 ManjaroOmen python3[612]: modprobe: FATAL: Module nvidia is in use.
Jan 15 20:24:24 ManjaroOmen python3[612]: [333] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
Jan 15 20:24:24 ManjaroOmen python3[612]: [333] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20210115T202423', 'requested_mode': 'intel'}
Jan 15 20:24:24 ManjaroOmen systemd[1]: Started Optimus Manager Commands Daemon.
Jan 15 20:24:24 ManjaroOmen python3[639]: [1] INFO: # Commands daemon
Jan 15 20:24:24 ManjaroOmen python3[639]: [2] INFO: Opening UNIX socket
Jan 15 20:24:24 ManjaroOmen python3[639]: [2] INFO: Awaiting commands
`

I think I should also mention that after doing this installation process, my space bar was rendered completely useless and my F1-F12 keys were working as if I had the FN key pressed all the time, while I had set otherwise in the BIOS long ago (at this point I already did a system restore).

For reference my laptop is a `OMEN by HP 15-ax201np` running Manjaro with kernel 5.10. The kernel 5.4 is also installed in this as a backup kernel.

**Comment by Aya-Komichi** [comment] 2021-01-25 22:24
Well, I am unsure if when I attempted to install optimus-manager I had installed optimus-manager-qt. Only a few days ago I found out that package was also needed since I use kde.

However I can no longer test if this would have worked for me since I have already moved to EndeavourOS. If you feel like the error I got isn't relevant in these conditions, feel free to close this issue.

**Comment by nwildner** [comment] 2024-07-01 11:21
Closing this case since the original reporter moved along and it might not be trivial to reproduce(case is 3+ years old)

**Closed by nwildner** 2024-07-01 11:21 UTC
