### ISSUE TITLE
10-optimus-manager.conf is not created when bbswitch is not loaded

### ISSUE THREAD

**Issue by Leeo97one** [Askannz/optimus-manager#136] opened 2019-09-22 13:21 UTC
**Describe the bug**
The `/etc/X11/xorg.conf.d/10-optimus-manager.conf` file is not created when the `bbswtich` module is not loaded because of a `KernelSetupError` exception.

As a quick (and dirty) fix, I changed the [`_unload_bbswitch()`](https://github.com/Askannz/optimus-manager/blob/v1.2/optimus_manager/kernel.py#L182) fonction to check if the module is loaded before trying to unload it: https://pastebin.com/3QdjnrPr

**System info**
- Distribution: Arch Linux
- Desktop manager: GNOME Shell
- Display manager: GDM
- Version: 1.2

**Logs**
`gpu_setup.log` before and after the patch: https://pastebin.com/iX9prEJW

**Comment by Askannz** [comment] 2019-09-27 09:13
Closing as a duplicate of https://github.com/Askannz/optimus-manager/issues/133.

**Closed** 2019-09-28 00:02 UTC
Labels: bug
