### ISSUE TITLE
Cannot switch or start in NVIDIA mode

### ISSUE THREAD

**Issue by lucadiliello** [Askannz/optimus-manager#225] opened 2020-03-03 15:10 UTC
**Describe the bug**
When turning on the system after having used `optimus-manager --set-startup nvidia`, GDM keeps asking me the password as it is was crashing. The only way I found to log in is to switch to terminal and type `optimus-manager --switch intel`. Then, after 2/3 tentatives, I can log in in `nvidia` mode (even if I switched to `intel`).

**System info**
Please include :
- Manjaro Linux - Release: 19.0.1
- GNOME
- GDM
- Razer Balde 2019, RTX 2080 MAX-Q
- the latest Git version (optimus-manager-git)

**Logs**
[prime_setup.log](https://github.com/Askannz/optimus-manager/files/4281965/prime_setup.log)
[gpu_setup.log](https://github.com/Askannz/optimus-manager/files/4281964/gpu_setup.log)
[boot_setup.log](https://github.com/Askannz/optimus-manager/files/4281963/boot_setup.log)

nvidia-enable.sh and nvidia-disable.sh are empty and I'm using the default config file with Runtime D3 (RTD3) Power Management. This logs seems not to be usefull...
I'm ready to give you other required info. 

UPDATE: I'm able to directly login in nvidia mode typing the password about 6 times. Which log can help you?

**Comment by Askannz** [comment] 2020-03-06 10:38
Just to be sure, have you followed all the instructions specific to GDM ?
https://github.com/Askannz/optimus-manager#important--gnome-and-gdm-users

**Comment by lucadiliello** [comment] 2020-03-11 14:41
Yes, I followed the instructions on switching to `gdm-prime` and so on...
What kind of logs should I provide?

**Comment by Askannz** [comment] 2020-06-07 01:10
Late reply, but could you try again with v1.3 ? If it still crashes on login, switch to a TTY, grab the latest log in `/var/log/optimus-manager/switch/` and post it here.

**Comment by nwildner** [comment] 2024-07-02 09:24
Hi @lucadiliello , how are things going?

Have you give it a try on `optimus-manager-git` and using a mode recent Kernel lately with this setup? Is the issue still reproducing?

Since this issue isn't active for the last 4 years ago and a lot has changed in many aspects of multiple software, we'll keep this case opened for some days and close it if no further comments are provided. We're dealing with backlog here to try to keep `optimus-manager` in a good shape and active as a project.

Have a nice week ahead.

**Closed** 2024-07-03 08:44 UTC
Labels: bug
