### ISSUE TITLE
When I switch to nvidia the screen resolution change.

### ISSUE THREAD

**Issue by fpaskali** [Askannz/optimus-manager#167] opened 2019-10-22 23:54 UTC
I am running Manjaro i3 on my laptop. optimus-manager works as it should, with a small problem, it changes the resolution of the screen. My native resolution is 1366x768, but when I switch to nvidia, it changes to 1024x768, and when I switch back to intel, the resolution is normal. 

I realized that it creates another output VGA-0, and fixed it by including "xrandr --output VGA-0 --off" in "/etc/optimus-manager/xsetup-nvidia.sh". But I would like to know if there is a way to completely avoid creating of this additional output. 

`xrandr -q    
                                                     
Screen 0: minimum 8 x 8, current 1366 x 768, maximum 16384 x 16384
VGA-0 connected (normal left inverted right x axis y axis)
   1024x768      60.00 +
   1600x900      59.82  
   1400x900      59.88  
   1368x768      59.88    59.85  
   1280x800      59.91    59.81  
   1280x720      59.86    59.74  
   1024x576      59.90    59.82  
   960x540       59.82    59.63  
   864x486       59.92    59.57  
   800x600       72.19    60.32    56.25  
   800x450       59.82  
   700x450       59.88  
   684x384       59.88    59.85  
   640x480       59.94  
   640x400       59.98    59.88  
   640x360       59.86    59.83  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.82    59.63  
   432x243       59.92    59.57  
   400x300       72.19  
   320x240       60.05  
LVDS-1-1 connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 344mm x 193mm
   1366x768      60.01*+
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   640x400       59.88    59.98  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
VGA-1-1 disconnected (normal left inverted right x axis y axis)
HDMI-1-1 disconnected (normal left inverted right x axis y axis)
DP-1-1 disconnected (normal left inverted right x axis y axis)`

**Comment by Askannz** [comment] 2020-03-07 00:10
Very late reply, but if you are still around:

You don't have any external monitor, right ? This is super strange that Intel and Nvidia modes are using different video outputs. I suspect your laptop is an old model with a muxed Optimus (there's a hardware switch that actively rewires the display to the active video card). What's the brand and model ?

If that's the case then it's surprising that optimus-manager works at all. I don't even know how to trigger the mux switch.

**Comment by fpaskali** [comment] 2020-03-07 09:19
I don't have any external monitor. I am not using Manjaro anymore, now I am using Arch, but the same issue persist and still I am using the same workaround. I have an older K53SV Asus laptop indeed, using legacy 390xx nvidia drivers, GPU is GeForce GT 540M. I also tried changing resolution on VGA-0 display, but this gave me poor performance, so I continued turning it off.

I am not sure what is muxed optimus, but I am using optimus-manager for some time now, and it works great, better than bumbleebee.

**Comment by cnekmp** [comment] 2020-06-14 22:22
Same issue on Dell XPS L502x laptop (GeForce GT 540M, Arch with bspwm). @fpaskali solution fixed my issue too. Thanks a lot.

**Comment by tuxinal** [comment] 2020-07-07 17:52
i have the same issue on the asus n53jf laptop (GeForce GT 425M) tho the solution provided here it got fixed but when i boot my mouse cursor is a little off-centered where the main output would show up without the solution but that isn't that bad i can live with it

**Comment by Zolyn** [comment] 2021-07-23 12:43
> i have the same issue on the asus n53jf laptop (GeForce GT 425M) though the solution provided here it got fixed but when i boot my mouse cursor is a little off-centered where the main output would show up without the solution but that isn't that bad i can live with it

Same issue on the asus k45vd laptop (GeForce GT 610M). @fpaskali solution fixed my problem and I used `xdotool` to move the mouse cursor to the center of the screen at startup.

```bash
xdotool mousemove 683 384
```
(The coordinates depend on your screen resolution. My screen resolution is 1366x768, so the coordinates are 683,384)

**Comment by nwildner** [comment] 2024-07-02 09:52
Sup Folks.

Since the original reporter provided the information that it is solved, and there is a workaround available for the "not centered mouse" situation, we'll be closing this case for the sake of keeping `optimus-manager`  project clean and ending some of the longstanding issues that might not reproduce after years of the case lingering in our queue.

Have a nice week.

**Closed by nwildner** 2024-07-02 09:52 UTC
Labels: bug, xrandr Prime ?
