### ISSUE TITLE
Logging out in nvidia mode in KDE + SDDM yields black screen after 1.3 update

### ISSUE THREAD

**Issue by kuroni** [Askannz/optimus-manager#262] opened 2020-05-26 00:32 UTC
**Describe the bug**
As the title, logging out while in `nvidia` mode in KDE + SDDM will yield a black screen. Ctrl + Alt + Fx works fine when the screen turned black, but attempting to restart SDDM will always yield a black screen.

**System info**
- Your distribution: Arch Linux
- Your desktop manager: KDE Plasma
- You display manager (SDDM, GDM, LightDM...): SDDM
- The version of optimus-manager you are using: stable release (optimus-manager 1.3 on AUR).
- Your custom optimus-manager configuration file at `/etc/optimus-manager/optimus-manager.conf`:

```
[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=yes

[nvidia]
DPI=
PAT=yes
modeset=yes
options=

[optimus]
auto_logout=no
switching=bbswitch
pci_power_control=no
pci_remove=no
pci_reset=no
startup_mode=auto
startup_auto_battery_mode=intel
startup_auto_extpower_mode=nvidia
```

**Additional information**:
I have checked through all of the logs (optimus-manager logs from the folder and from `journalctl`, SDDM's `journalctl`'s log, kernel log, Xorg's log, etc.) and nothing seems to be out of order (SDDM reports that the greeter started normally, optimus-manager didn't pick up the logout).

However, I have tried the following combinations and all of them worked well:
* Logging out from `intel` mode.
* Switching from `intel` to `nvidia` and vice versa.
* Switching from `intel` to `intel`.
* Switching from `nvidia` to `nvidia`.

EDIT: This is not the case when using version 1.2.2.

**Comment by hacker1024** [comment] 2020-05-26 01:54
I get this too, with Cinnamon + LightDM.

**Comment by luchiago** [comment] 2020-05-26 12:48
+1, with Manjaro 20.0.1 GNOME. Sometimes, when I set to startup with Nvidia, it yields a blank screen, and I can't insert commands or fix, just force restart. The same happens when I switch once for Nvidia while I'm logged into the system.

**Comment by hacker1024** [comment] 2020-05-26 13:20
@luchiago You should still be able to switch to a terminal TTY (CTRL + ALT + F2) and safely reboot from there

**Comment by luchiago** [comment] 2020-05-26 13:41
@hacker1024 The problem is that wasn't able to do this either.

**Comment by natsukagami** [comment] 2020-05-26 23:35
Could it be a mesa thing? Try downgrading mesa...

**Comment by kuroni** [comment] 2020-05-26 23:58
I'm now certain that this is a thing with the 1.3 update. I tried downgrading to 1.2.2 and there are no black screens.

**Comment by luchiago** [comment] 2020-05-26 23:59
@kuroni the problem for me it's with this version

**Comment by Hyper-KVM** [comment] 2020-05-29 05:18
The reason why this is happening is because the pre_xorg_start hook only runs if switching GPUs or after pre_daemon_start hook.

**Comment by kuroni** [comment] 2020-05-29 19:32
Nice! Out of curious though, why does it work for `intel` mode when the hook doesn't run?

**Comment by Hyper-KVM** [comment] 2020-05-29 21:42
> Nice! Out of curious though, why does it work for `intel` mode when the hook doesn't run?

Intel and Hybrid mode does not need xrandr commands to be run for the screen to function as the intel GPU is the main display device connected to the laptop display.

**Comment by jacob-swenson** [comment] 2020-05-30 04:12
I have the same issue using LightDM+i3wm.

**Comment by daniel65dj** [comment] 2020-06-01 22:17
Same issue with Manjaro KDE and awesome wm.

**Comment by Doaxan** [comment] 2020-06-04 10:34
Same here with xfce, bspwm, lightdm\sddm.

**Comment by Askannz** [comment] 2020-06-06 06:31
@Hyper-KVM was 100% right about the cause, there was an issue with the state logic causing Prime screen offloading to not be set up again after a logout.

Should be fixed in -git now, let me know how that goes.

**Comment by hacker1024** [comment] 2020-06-07 03:25
Fixed for me, thanks!

**Comment by Askannz** [comment] 2020-06-08 07:22
I'll assume it's fixed, feel free to reopen otherwise.

**Closed by Askannz** 2020-06-08 07:22 UTC
