### ISSUE TITLE
Qt Scaling Resets in Kde Plasma

### ISSUE THREAD

**Issue by gikari** [Askannz/optimus-manager#208] opened 2020-01-31 18:58 UTC
#### Describe the bug

After switching to Nvidia mode scaling in Qt apps resets.

#### Steps to Reproduce

1. Start KDE Plasma in Intel Mode
1. Set scaling to any value more than 1 (I used 1.25)
1. Relogin into session and see, that Dolphin uses new scale (both font and other UI elements)
1. Relogin in Nvidia Mode via Optimus Manager (I use Qt tray app)
1. Open Dolphin and see, that **only fonts** are scaled (probably because I set DPI in optimus-manager-qt Nvidia category to 120), but not the other UI elements (buttons etc). 
1. Open Plasma scaling settings and change the scale to the one, previously used for Intel Mode (1.25 in my case)
1. Relogin and see, that Dolphin elements are correctly scaled.

#### Expected behavior

The scaling is saved between sessions before and after switching.

#### System info
- Switching method: bbswitch
- Manjaro
- KDE Plasma
- SDDM
- optimus-manager 1.2.2-2.2

#### Workaround
I [acknowledge](https://github.com/Askannz/optimus-manager/issues/154#issuecomment-540696226), that I can workaround the bug via
```
export QT_SCREEN_SCALE_FACTORS=$QT_SCREEN_SCALE_FACTORS"eDP-1-1=1.25"
```
in `~/.config/plasma-workspace/env/test.sh` file, but I think scaling saving should be done automatically and in a less hacky way. Not sure how and where (on optimus-manager side or on Kde Plasma side) this should be done though.

**Comment by Askannz** [comment] 2020-02-15 07:55
As mention in the other issue, the root of the problem is that the video output corresponding to the laptop screen is named differently in Intel and Nvidia mode. On my machine for example, it's `eDP-1` with Intel and `eDP-1-1` with Nvidia.

When you set the scale in KDE settings, it sets the env variable `QT_SCREEN_SCALE_FACTORS` and assigns the global scale factor to each video ouput it can find. But when you switch GPU mode, the output name changes, the env variable doesn't apply and the scaling resets to its default value of 1.0.

This is not specific to Nvidia, you can reproduce the same issue by setting the scale in Nvidia mode and then switching to Intel.

I don't know if there is a proper way to fix this, to be honest. Ideally, this would be fixed upstream by making KDE enumerate outputs on every startup (rather than once when configuring the scale), but I doubt they're going to bother.

A feasible (but hacky) option for us could be to have optimus-manager inject itself at session startup and automatically "fix" the environment variable. Can't say I'm really fond of that idea though.

**Comment by nwildner** [comment] 2024-07-02 12:58
Hi @gikari . Is this issue still under your radar ?  Are you still able to reproduce?

As @Askannz said, there is no easy fix for this and monitors can change the naming indeed. On my laptop, it will be named `eDP1`, `eDP1-1` or `eDP0` depending if I'm using `integrated/hybrid` or `nvidia` and also if I use the dedicated (or ultimate)  mode on bios.

Maybe you'll have to make a script to probe the current built-in monitor like this:

```
xrandr | grep eDP | awk '{print $1}'
eDP-1
``` 

Or, make this command the output of a variable and use it to feed the `QT_SCREEN_SCALE_FACTORS` with something like this: 

```
BUILT_SCREEN=`xrandr | grep eDP | awk '{print $1}' `
export QT_SCREEN_SCALE_FACTORS="$QT_SCREEN_SCALE_FACTORS;$BUILT_SCREEN=1.25"
```

Also, there is the fact that the [QT_SCREEN_SCALE_FACTORS](https://doc.qt.io/qt-5/highdpi.html) deals with an array of monitors as per documentation so, this could also be a valid way to assign to multiple monitors: 

```
export QT_SCREEN_SCALE_FACTORS="$QT_SCREEN_SCALE_FACTORS;eDP-1=1.25;eDP-1-1=1.25"
```

While this might lock "hacky" as you've said, this isn't something that is under `optimus-manager` control but rather it is a known behavior of when you use `nvidia` with KDE/Plasma

 -  [Scale gets screwy with QT when using Nvidia driver + KDE + X11](https://www.reddit.com/r/kde/comments/1d3xti3/scale_gets_screwy_with_qt_when_using_nvidia/)

Since this issue isn't active for the last 4 years ago and a lot has changed in many aspects of multiple software, we'll be closing this case. We're dealing with backlog here to try to keep `optimus-manager` in a good shape and active as a project.

Have a nice week ahead.

**Closed by nwildner** 2024-07-02 12:58 UTC
Labels: bug
